// Author-written revisions. IDs and earned progress stay stable across revisions.
const step = (code, explanation) => ({ code, explanation });
export function applyCurriculumReview(modules) {
  const all = Object.fromEntries(modules.flatMap(m => m.lessons).map(l => [l.id, l]));
  const edit = (id, patch) => Object.assign(all[id], patch);
  edit('ola', {
    theory: ['Sintaxe é a forma de escrever uma instrução para o Python entender. Começaremos com uma única instrução: mostrar um texto.', 'Escreva print em minúsculas, abra um parêntese, coloque o texto entre aspas e feche o parêntese. Em print("Olá!"), as aspas delimitam o texto; elas não aparecem na saída.', 'Cada instrução fica em uma linha. Enter cria a próxima linha. Uma linha iniciada por # é um comentário para a pessoa que lê: Python não a executa. Aqui ainda não precisamos de contas, condições ou indentação.'],
    example: 'print("Olá!")\nprint("Estou aprendendo.")',
    starter: '# Escreva print, abra os parênteses e coloque a frase entre aspas.\n',
    walkthrough: [step('print("Olá!")', 'print é o nome do comando. ( e ) envolvem a informação que será mostrada. "Olá!" é um texto. A saída desta linha é Olá!.'), step('print("Estou aprendendo.")', 'Depois da primeira linha, o Python executa esta. Cada print coloca sua mensagem em uma linha da saída.')],
    hints: ['Use a estrutura print("seu texto"). Troque apenas o texto dentro das aspas pela frase do enunciado.', 'Confira se fechou as aspas antes de fechar o parêntese. Não escreva Print com P maiúsculo.']
  });
  edit('variaveis', {
    theory: ['Uma variável é um nome que usamos para acessar um valor. A sintaxe é nome = valor. Leia o sinal = como "recebe". Python resolve o lado direito e associa o resultado ao nome do lado esquerdo.', 'Em nome = "Ana", nome é a variável e "Ana" é o texto guardado. print(nome) mostra Ana. Já print("nome") mostra literalmente a palavra nome. Para acessar uma variável, não coloque seu nome entre aspas.', 'Crie a variável antes de usá-la: o programa lê de cima para baixo. Escreva um nome sem espaços, como linguagem ou nome_aluno. Maiúsculas e minúsculas são diferentes. Por enquanto, atribua um valor em uma linha e mostre-o na próxima.'],
    example: 'nome = "Ana"\nprint(nome)',
    starter: '# 1. Crie linguagem usando = e o texto entre aspas.\n# 2. Mostre a variável com print, sem aspas no nome.\n',
    walkthrough: [step('nome = "Ana"', 'O valor à direita é o texto Ana. Ele fica associado ao nome nome. Esta linha sozinha não mostra nada.'), step('print(nome)', 'Python procura o valor associado a nome e o entrega ao print. A saída é Ana.')],
    hints: ['A primeira linha segue o modelo linguagem = "texto". O valor pedido é Python.', 'Na segunda linha, use print(linguagem), sem colocar linguagem entre aspas.']
  });
  edit('tipos', {
    theory: ['Um tipo indica a espécie de valor. "21" é texto (str), porque está entre aspas. 21 é inteiro (int), sem aspas. 7.5 é decimal (float), com ponto. True e False são booleanos (bool), escritos com inicial maiúscula e sem aspas.', 'Converter é criar um valor de outro tipo. A sintaxe numero = int(texto) pede que int leia o texto e devolva um inteiro. Guarde esse retorno em outra variável; isso deixa visível o que é texto e o que é número.', 'type(valor) informa o tipo. print(type(numero)) significa: primeiro descubra o tipo de numero; depois mostre a resposta. A saída <class \'int\'> é a maneira como Python exibe o tipo inteiro. Você não precisa escrever class.', 'Nesta aula não faremos contas. Primeiro vamos criar, converter e inspecionar valores. A próxima aula ensina como montar uma conta com os operadores. int só aceita textos que representam inteiros: int("abc") gera um erro chamado ValueError.'],
    example: 'texto = "12"\nnumero = int(texto)\nprint(numero)\nprint(type(numero))',
    challenge: 'Converta o texto "21" para inteiro e guarde em numero. Mostre numero e, na linha seguinte, o tipo de numero. Não precisa fazer nenhuma conta.',
    starter: 'texto = "21"\n# 1. Converta texto e guarde em numero.\n# 2. Mostre numero.\n# 3. Mostre type(numero).\n',
    expected: "21\n<class 'int'>",
    walkthrough: [step('texto = "12"', 'As aspas tornam 12 um texto. A variável texto continua sendo texto mesmo depois da conversão da próxima linha.'), step('numero = int(texto)', 'int(texto) transforma o texto "12" no inteiro 12. O sinal = guarda esse inteiro em numero.'), step('print(numero)', 'Mostra o valor convertido: 12.'), step('print(type(numero))', 'A chamada interna type(numero) é resolvida primeiro. print mostra <class \'int\'>. Os dois parênteses finais fecham type e print.')],
    hints: ['Use a variável fornecida: numero = int(texto). Não precisa multiplicar nem somar.', 'São dois prints: o primeiro mostra numero; o segundo mostra type(numero). Compare as duas linhas com a saída esperada.']
  });
  edit('operadores', {
    theory: ['Agora que você sabe criar números e variáveis, vamos montar uma conta. A sintaxe resultado = primeiro_numero * segundo_numero calcula o lado direito e guarda o resultado. O símbolo * significa multiplicação; não se escreve x para multiplicar em Python.', 'Os operadores básicos são + (somar), - (subtrair), * (multiplicar) e / (dividir). Por exemplo: 6 + 2 resulta em 8; 6 - 2 em 4; 6 * 2 em 12; 6 / 2 em 3.0. A divisão / produz um decimal.', 'Comece com uma operação por linha. subtotal = quantidade * preco calcula a compra; total = subtotal - desconto aplica o desconto; print(total) mostra a resposta. Use nomes como produto, subtotal ou total. O nome soma não muda a operação: quem define a conta é o símbolo.', 'Em expressões combinadas, * e / vêm antes de + e -. Parênteses mudam essa ordem: (2 + 3) * 4 resulta em 20. Mais adiante também usaremos // para divisão inteira, % para resto e ** para potência; por exemplo 7 // 2 é 3, 7 % 2 é 1 e 3 ** 2 é 9.'],
    example: 'quantidade = 2\npreco = 10\ndesconto = 3\nsubtotal = quantidade * preco\ntotal = subtotal - desconto\nprint(total)',
    starter: 'quantidade = 3\npreco = 20\ndesconto = 5\n# 1. Calcule subtotal com quantidade * preco.\n# 2. Calcule total retirando o desconto.\n# 3. Mostre total.\n',
    question: 'Qual símbolo faz uma multiplicação em Python?', options: ['*', 'x', '+'], answer: 0,
    walkthrough: [step('quantidade = 2\npreco = 10\ndesconto = 3', 'Primeiro definimos os três valores, sem aspas: são números.'), step('subtotal = quantidade * preco', 'Python busca 2 e 10, calcula 2 * 10 e guarda 20 em subtotal.'), step('total = subtotal - desconto', 'Usa o subtotal já calculado: 20 - 3. Guarda 17 em total.'), step('print(total)', 'Mostra 17. A conta e a apresentação ficaram em linhas separadas para facilitar a leitura.')],
    hints: ['Faça primeiro subtotal = quantidade * preco. Multiplicação usa *.', 'Na próxima linha, retire desconto de subtotal com -. Depois use print(total).']
  });
  edit('strings', {
    theory: ['Um texto é uma string. Um método é uma operação ligada a um valor. Para chamá-lo, escreva o texto ou variável, um ponto, o nome do método e parênteses: texto.upper(). upper transforma letras em maiúsculas; lower, em minúsculas.', 'strip() remove espaços das extremidades. Esses métodos devolvem outro texto: guarde o resultado em uma variável. Primeiro use uma operação por linha, em vez de encadear várias chamadas.', 'len(texto) conta caracteres. Você também pode unir textos com +. Uma f-string começa com f antes das aspas e insere uma variável entre chaves: f"Olá, {nome}". Para mostrar um decimal com duas casas, use f"{preco:.2f}". A formatação muda a apresentação, não o valor.'],
    example: 'texto = "  ana  "\nlimpo = texto.strip()\nmaiusculo = limpo.upper()\nprint(maiusculo)',
    walkthrough: [step('texto = "  ana  "', 'Os espaços entre as aspas também fazem parte do texto.'), step('limpo = texto.strip()', 'O ponto liga strip ao texto. Os parênteses chamam o método. O novo texto "ana" fica em limpo.'), step('maiusculo = limpo.upper()', 'Agora aplicamos upper ao texto já limpo e guardamos "ANA".'), step('print(maiusculo)', 'Mostra ANA. texto ainda contém o valor original; as outras variáveis guardam os resultados.')],
    hints: ['Crie limpo = texto.strip() para remover os espaços nas pontas.', 'Aplique .upper() ao texto limpo e imprima esse resultado. Não é necessário usar .title().']
  });
  edit('entrada', {
    theory: ['input() recebe uma linha digitada e a devolve como texto. A sintaxe resposta = input() guarda esse texto. No laboratório, execute o código e responda no campo que aparece abaixo do editor. Se preencher Entradas para input() antes, essas linhas serão usadas automaticamente.', 'Para trabalhar com número, faça em etapas: texto = input(), numero = int(texto), print(numero). Se precisar de decimal, use float(texto). As chamadas aninhadas int(input()) fazem o mesmo trabalho, mas separar ajuda a entender cada passo.', 'No desafio, responda 21 quando o programa pedir. Experimente outra resposta depois de concluir. Para uma mensagem de orientação, pode usar input("Digite um número: "); input() sem mensagem também espera uma resposta, mas não escreve uma pergunta. No modo interativo da plataforma, a pergunta aparece em um campo separado da saída.', 'Uma entrada como abc não pode virar inteiro e gera ValueError. Por enquanto, teste com a entrada válida pedida. A aula "Tratando exceções" ensinará a capturar esse erro; você ainda não precisa escrever try/except.'],
    example: 'texto = input()\nnumero = int(texto)\nprint(numero)',
    stdin: '21',
    challenge: 'Leia a entrada 21 com input(), converta o texto lido em inteiro e mostre o número. Use 21 como resposta ao executar. Não escreva o 21 direto no código: ele precisa chegar pelo input().',
    starter: '# 1. Leia uma linha com input() e guarde em texto.\n# 2. Converta texto em numero.\n# 3. Mostre numero.\n', expected: '21',
    walkthrough: [step('texto = input()', 'Espera sua resposta. Se você digitar 21, guarda o texto "21". Ainda não é um número.'), step('numero = int(texto)', 'Reutiliza a conversão que você aprendeu na aula de tipos: texto vira inteiro.'), step('print(numero)', 'Mostra 21. Se a entrada fosse 30, o mesmo programa mostraria 30 sem mudar o código.')],
    hints: ['Use texto = input(). Depois de executar, digite 21 no campo de resposta.', 'Converta o valor que foi lido, com int(texto). Em seguida, imprima a variável numérica.']
  });
  edit('condicoes', {
    theory: ['Primeiro vem a comparação: >= significa "maior ou igual", > significa "maior", <= significa "menor ou igual", < significa "menor", == compara igualdade e != compara diferença. O resultado é True ou False. O sinal = sozinho continua servindo para atribuir um valor.', 'A sintaxe é if condição: e, na linha seguinte, quatro espaços antes da instrução. Os dois-pontos abrem o bloco; os espaços mostram quais instruções pertencem a ele. elif e else voltam ao alinhamento do if. Use Tab no nosso editor para inserir quatro espaços.', 'Python testa de cima para baixo. Ao encontrar a primeira condição verdadeira, executa aquele bloco e pula os outros. elif só é testado se as condições anteriores falharem. else não recebe condição: pega o caso restante. Sem else, é possível nenhum bloco executar.', 'Comece com dois caminhos, no simulador baseado no PDF: nota >= 6 aprova. Depois escolha o modo com três caminhos. O exemplo abaixo usa uma regra fictícia: >= 7 aprova, de 5 até menos de 7 recupera e abaixo de 5 reprova. Teste >= 7 antes de >= 5, porque todo número >= 7 também é >= 5.'],
    example: 'nota = 8\nif nota >= 7:\n    print("Aprovado")\nelif nota >= 5:\n    print("Recuperação")\nelse:\n    print("Reprovado")',
    walkthrough: [step('nota = 8', 'Guarda a nota numérica. Você pode mudar só esse valor para testar outros caminhos.'), step('if nota >= 7:\n    print("Aprovado")', '8 >= 7 é verdadeiro. Executa o print que tem quatro espaços à esquerda.'), step('elif nota >= 5:\n    print("Recuperação")', 'Não é testado para nota 8, pois o if já foi verdadeiro. Para nota 6, o if falha e este elif é verdadeiro.'), step('else:\n    print("Reprovado")', 'Não leva condição depois de else. Para nota 4, os testes anteriores falham e este bloco executa.')],
    hints: ['Comece pelo limite maior: if nota >= 7:. Depois escreva elif nota >= 5:.', 'Escreva apenas else: no último caminho. Cada print fica com quatro espaços. Para nota 6, a saída é Recuperação.']
  });
  edit('booleanos', {
    theory: ['and exige que as duas condições sejam verdadeiras. or exige pelo menos uma. not inverte um booleano. Comece guardando cada comparação em uma variável para enxergar quais valores você está combinando.', 'idade >= 18 devolve um booleano. tem_ingresso = True já guarda um booleano. permitido = maior_de_idade and tem_ingresso combina os dois. Só existe permissão se ambos forem True.', 'Na versão compacta você pode escrever permitido = idade >= 18 and tem_ingresso. Parênteses ajudam a separar condições maiores. Não confunda and com &: neste momento estamos combinando condições, não bits.'],
    example: 'idade = 19\ntem_ingresso = True\nmaior_de_idade = idade >= 18\npermitido = maior_de_idade and tem_ingresso\nprint(permitido)',
    challenge: 'Uma pessoa pode entrar se tiver pelo menos 18 anos e tiver ingresso. Use and para combinar as duas condições e mostre o resultado.',
    starter: 'idade = 20\ntem_ingresso = True\n# Compare a idade e combine com tem_ingresso usando and.\n',
    walkthrough: [step('idade = 19\ntem_ingresso = True', 'A primeira variável é um número; a segunda já é um booleano, sem aspas.'), step('maior_de_idade = idade >= 18', 'A comparação é verdadeira. Guardamos True em maior_de_idade.'), step('permitido = maior_de_idade and tem_ingresso\nprint(permitido)', 'Combina True and True e mostra True. Se um deles fosse False, o resultado seria False.')],
    hints: ['Separe a comparação: maior_de_idade = idade >= 18.', 'Combine maior_de_idade and tem_ingresso e mostre o resultado. Não precisa pesquisar caracteres de uma senha.']
  });
  edit('for', {
    theory: ['for repete um bloco usando um valor por vez. Em for numero in range(1, 4):, range fornece 1, 2 e 3; numero recebe cada um, na ordem. O limite final 4 não entra. in aqui liga a variável aos valores que serão percorridos.', 'Use dois-pontos no fim da linha do for e quatro espaços nas instruções repetidas. Uma linha que volta ao alinhamento do for fica fora do laço e só executa depois que ele terminar.', 'Um acumulador começa com um valor antes do laço. total = total + numero significa: leia o total anterior, some o numero atual e guarde o resultado em total. Não reinicie total dentro do laço. total += numero é uma abreviação dessa atualização; primeiro use a forma completa.'],
    example: 'total = 0\nfor numero in range(1, 4):\n    total = total + numero\nprint(total)',
    walkthrough: [step('total = 0', 'Inicializa o acumulador uma vez, antes das repetições.'), step('for numero in range(1, 4):', 'Vai passar por 1, 2 e 3. Quando range acabar, sai do laço.'), step('    total = total + numero', 'Primeira passagem: 0 + 1 = 1. Segunda: 1 + 2 = 3. Terceira: 3 + 3 = 6.'), step('print(total)', 'Sem os quatro espaços, este print está fora do laço. Mostra somente o resultado final: 6.')],
    hints: ['Para incluir o 5, o limite final de range deve ser 6: range(1, 6).', 'Atualize total dentro do for e deixe print(total) fora dele, sem indentação.']
  });
  edit('while', {
    example: 'contador = 3\nwhile contador > 0:\n    print(contador)\n    contador = contador - 1',
    walkthrough: [step('contador = 3', 'Define o ponto de partida antes do laço.'), step('while contador > 0:', 'Testa a condição antes de cada repetição. Ela precisa se tornar falsa para o laço terminar.'), step('    print(contador)\n    contador = contador - 1', 'Mostra o valor e depois reduz 1. As saídas são 3, 2 e 1. Quando contador chega a 0, a condição fica falsa.')],
    hints: ['Neste desafio a contagem sobe: repita enquanto numero <= 3.', 'Dentro do laço, mostre numero e faça numero = numero + 1. Sem essa atualização ele não termina.']
  });
  edit('funcoes', {
    walkthrough: [step('def dobro(numero):', 'def cria uma função chamada dobro. numero é o parâmetro: receberá o argumento usado na chamada. Os dois-pontos abrem o corpo.'), step('    return numero * 2', 'O corpo tem quatro espaços. Calcula o dobro e devolve o resultado para quem chamou. return não mostra nada na saída.'), step('print(dobro(6))', 'A chamada dobro(6) entrega 6 a numero. A função devolve 12 e print mostra 12.')],
    hints: ['No corpo de quadrado, devolva numero * numero. Multiplicar um número por ele mesmo calcula o quadrado.', 'Substitua pass por return e sua expressão. pass é apenas um marcador que não faz nada; o print da chamada já está fornecido.']
  });
  edit('decomposicao', {
    theory: ['Decompor é dividir um problema em passos pequenos. Para calcular uma média de três notas: receber três números, somá-los, dividir por 3 e mostrar a resposta. Antes de programar, descreva essa sequência.', 'Uma função pode receber vários parâmetros separados por vírgulas: def media(a, b, c):. Ao chamar media(6, 8, 10), a recebe 6, b recebe 8 e c recebe 10. Guarde a soma em total e devolva total / 3.', 'Aqui usamos somente números e funções, que já foram apresentados. Listas, len e sum serão estudados nas próximas aulas. Verifique um caso comum e também os limites: três zeros, por exemplo, devem produzir 0.0.'],
    example: 'def media(a, b, c):\n    total = a + b + c\n    return total / 3\n\nresultado = media(6, 8, 10)\nprint(resultado)',
    challenge: 'Complete media(a, b, c) para somar três notas e dividir por 3. A chamada com 7, 8 e 9 já está pronta. Não precisa usar uma lista.',
    starter: 'def media(a, b, c):\n    # Calcule total e depois devolva total / 3.\n    pass\n\nprint(media(7, 8, 9))',
    walkthrough: [step('def media(a, b, c):', 'Três parâmetros separados por vírgulas recebem três números na ordem da chamada.'), step('    total = a + b + c\n    return total / 3', 'Primeiro soma, depois divide. Separar as linhas deixa a ordem explícita.'), step('resultado = media(6, 8, 10)\nprint(resultado)', '6 + 8 + 10 resulta em 24; 24 / 3 resulta em 8.0. print mostra o retorno guardado em resultado.')],
    hints: ['Use total = a + b + c dentro da função, com quatro espaços.', 'Na linha seguinte do corpo, escreva return total / 3. A função já será chamada pelo código inicial.']
  });
  edit('listas', { example: 'numeros = [10, 20]\nnumeros.append(30)\ntotal = sum(numeros)\nprint(total)', walkthrough: [step('numeros = [10, 20]', 'Os colchetes criam uma lista. Vírgulas separam os elementos. numeros[0] acessaria 10; numeros[1] acessaria 20.'), step('numeros.append(30)', 'append adiciona 30 no fim da mesma lista. A lista agora contém 10, 20 e 30.'), step('total = sum(numeros)\nprint(total)', 'sum soma os valores numéricos de uma sequência. Aqui devolve 60. len(numeros), por sua vez, contaria os três elementos.')], hints: ['Use numeros.append(40). Não atribua o retorno de append à lista.', 'sum(numeros) calcula a soma de todos os elementos. Guarde ou imprima esse retorno.'] });
  edit('dicionarios', { example: 'produto = {"nome": "Livro", "estoque": 3}\nestoque_atual = produto["estoque"]\nproduto["estoque"] = estoque_atual + 2\nprint(produto["estoque"])', walkthrough: [step('produto = {"nome": "Livro", "estoque": 3}', 'Chaves delimitam o dicionário. Cada par usa chave: valor, e vírgulas separam os pares.'), step('estoque_atual = produto["estoque"]', 'Os colchetes recebem a chave, aqui o texto "estoque", e devolvem 3.'), step('produto["estoque"] = estoque_atual + 2\nprint(produto["estoque"])', 'Atualiza somente esse valor do dicionário para 5 e consulta a mesma chave para mostrar 5.')], hints: ['Leia produto["estoque"] e some 5 ao valor atual.', 'Guarde o resultado na mesma chave, produto["estoque"], e imprima o valor atualizado.'] });
  edit('conjuntos', { walkthrough: [step('a = {1, 2, 3}\nb = {3, 4}', 'Chaves com valores sem pares chave: valor criam conjuntos. Eles não repetem elementos. set(lista) converte uma lista em conjunto.'), step('print(sorted(a & b))', '& entre conjuntos calcula a interseção: os elementos presentes nos dois. sorted devolve uma lista ordenada para a saída ter ordem previsível. Aqui mostra [3].')], hints: ['Use unicos = set(numeros) para eliminar duplicatas.', 'sorted(unicos) transforma o conjunto em uma lista ordenada. Mostre essa lista.'] });
  edit('comprehensions', { walkthrough: [step('dobros = [n * 2 for n in range(4)]', 'Leia primeiro for n in range(4): n passa por 0, 1, 2 e 3. Para cada n, a expressão à esquerda calcula n * 2. Os colchetes recolhem os resultados.'), step('print(dobros)', 'A lista pronta é [0, 2, 4, 6]. Um if após a origem poderia filtrar valores; a forma seria [n * 2 for n in range(4) if n > 1].')], hints: ['Percorra range(1, 5) para incluir de 1 a 4.', 'Use n * n como a expressão à esquerda de for dentro dos colchetes. Depois imprima a lista.'] });
  edit('ordenacao', { example: 'precos = [12, 5, 20]\nordenados = sorted(precos, reverse=True)\nprint(ordenados)', walkthrough: [step('precos = [12, 5, 20]', 'Define a lista original. sorted não a altera.'), step('ordenados = sorted(precos, reverse=True)', 'O argumento nomeado reverse=True pede a ordem inversa, do maior para o menor. O sinal = aqui informa um argumento da chamada.'), step('print(ordenados)', 'Mostra [20, 12, 5]. A versão com key=lambda será uma extensão explicada na sintaxe desta aula.')], hints: ['Passe reverse=True para sorted, junto com precos.', 'Imprima a nova lista retornada por sorted; precos ainda estará na ordem original.'] });
  edit('complexidade', { walkthrough: [step('def contem(itens, alvo):', 'Recebe uma lista e o valor procurado.'), step('    for item in itens:\n        if item == alvo:\n            return True', 'Percorre um item por vez. Os blocos aninhados têm 4, 8 e 12 espaços. Ao achar, return sai da função imediatamente.'), step('    return False', 'Só chega aqui se terminou o for sem encontrar o alvo. Está no corpo da função, mas fora do laço.'), step('print(contem([1, 4, 7], 4))', 'Mostra True. No pior caso precisa olhar toda a lista: o trabalho cresce com a quantidade de itens.')], hints: ['Crie contagem = 0 antes do for. Dentro do for, compare cada item com 2.', 'Só quando item == 2, faça contagem = contagem + 1. Imprima contagem depois do laço.'] });

  // Bridges for syntax that previously appeared before its teaching point.
  all.funcoes.theory.push('A palavra pass significa "não faça nada" e permite deixar um corpo provisório sem erro de sintaxe. No desafio, ela deve ser substituída pelo return. O corpo de uma função só roda quando a função é chamada.');
  all.listas.theory.push('A sintaxe de criação é [valor1, valor2]. sum(lista) soma elementos numéricos e len(lista) conta elementos. append(valor) altera a lista e não devolve a lista: não escreva numeros = numeros.append(40).');
  all.ordenacao.theory.push('Para ordenar dicionários por uma chave, key recebe uma função que extrai o critério. Em key=lambda p: p["idade"], p é cada dicionário, : separa o parâmetro da expressão e p["idade"] é o valor usado na ordenação. Comece pelo exemplo simples com reverse; essa forma é uma extensão para praticar depois.');
  all.encapsulamento.example = all.encapsulamento.example.replace('raise ValueError("Valor deve ser positivo")', 'return False').replace('self._saldo += valor', 'self._saldo = self._saldo + valor');
  all.encapsulamento.theory.push('Neste primeiro exemplo, o depósito inválido encerra o método com return False. Não usamos raise antes da aula de exceções. @property na linha imediatamente anterior ao método saldo permite ler c.saldo sem escrever c.saldo().');
  all.excecoes.theory = [
    'Uma conversão pode falhar: int("abc") não consegue produzir um número. Coloque a ação dentro de try:. Se acontecer ValueError, Python pula para except ValueError: e executa a resposta que você escreveu ali.',
    'Seu programa também pode recusar um valor que desrespeita uma regra. if valor <= 0: confere a regra; raise ValueError("Valor deve ser positivo") avisa que ela foi desrespeitada. raise interrompe o caminho normal naquele ponto. O except correspondente pode tratar esse aviso, como faz com um erro de conversão.',
    'No exemplo, observe primeiro o erro de conversão. Depois veja uma regra que recusa -1. Troque só valor por 10 e execute novamente: a segunda parte deve mostrar 10. Teste também 0 antes de usar essa ideia no simulador de conta.',
    'Use o tipo de erro que você espera tratar, como ValueError ou ZeroDivisionError. finally é um bloco adicional para uma limpeza que deve acontecer mesmo com erro; não precisamos dele neste exercício.'
  ];
  all.excecoes.example = 'try:\n    numero = int("abc")\nexcept ValueError:\n    print("Digite um número inteiro")\n\nvalor = -1\ntry:\n    if valor <= 0:\n        raise ValueError("Valor deve ser positivo")\n    print(valor)\nexcept ValueError:\n    print("Valor deve ser positivo")';
  all.dataclasses.theory.unshift('Antes da classe, from dataclasses import dataclass carrega um recurso pronto. Leia: "do módulo dataclasses, importe dataclass". @dataclass aplica esse recurso à classe logo abaixo. nome: str declara um campo chamado nome com tipo esperado texto; preco: float declara um campo numérico decimal. O : aqui é uma anotação, não um bloco.');
  all.json.theory.unshift('import json disponibiliza o módulo com esse nome. Depois, json.loads(texto) chama loads dentro dele. Esta é a outra forma de importação: com from módulo import recurso você usa o recurso direto; com import módulo você escreve módulo.recurso.');
  all.csv.theory.push('import io disponibiliza StringIO: io.StringIO(texto) cria um arquivo de texto em memória. Na string, \\n representa uma quebra de linha. O cabeçalho define as chaves de cada linha. Para somar uma coluna, use acumulador e int(linha["valor"]), pois a célula vem como texto.');
  all.sql.theory.push('con.execute recebe o comando SQL como texto. O placeholder ? recebe o dado separado, no segundo argumento: ("Ana",) é uma tupla de um elemento; a vírgula é necessária. fetchone() obtém uma linha da consulta e [0] pega a primeira coluna. con.close() fecha a conexão.');
  all.transacoes.theory.push('executemany recebe uma lista de tuplas, uma por registro. SUM(valor), dentro do texto SQL, soma a coluna no banco; não é o sum de Python. Depois de consultar, fetchone()[0] extrai esse total.');
  all.rest.example = 'tarefas = [{"id": 1, "titulo": "Estudar"}]\ndef buscar_tarefa(tarefa_id):\n    for tarefa in tarefas:\n        if tarefa["id"] == tarefa_id:\n            return tarefa\n    return None\n\nprint(buscar_tarefa(1)["titulo"])';
  all.validacao.theory.push('isinstance(valor, str) testa se um valor é texto. Um texto vazio é falso em uma condição, então not nome.strip() identifica um nome vazio após remover espaços. raise ValueError("mensagem") cria a falha; quem chama pode tratá-la com except ValueError.');
  all.autenticacao.example = 'def pode_editar(usuario_id, dono_id, admin=False):\n    return usuario_id == dono_id or admin\n\nprint(pode_editar(3, 3))';
  all.autenticacao.theory.push('admin=False no cabeçalho é um valor padrão: quando a chamada omite o terceiro argumento, admin recebe False. usuario_id == dono_id or admin permite o dono ou um administrador. Este exercício pratica autorização; não implementa login ou armazenamento de senhas.');
  all.paginacao.example = 'itens = list(range(1, 11))\npagina = 2\ntamanho = 3\ninicio = (pagina - 1) * tamanho\nfim = inicio + tamanho\nprint(itens[inicio:fim])';
  all.paginacao.theory.push('list(range(...)) transforma os valores de range em uma lista. A sintaxe lista[inicio:fim] é um fatiamento: inclui inicio e exclui fim. Para inicio = 3 e fim = 6, pega os índices 3, 4 e 5. Não confunda índices começando em zero com páginas começando em um.');
  // Keep the Python union symbol inside the paragraph; the base text delimiter is |.
  all.tipagem.theory = [
    'Anotações documentam os tipos esperados. Em def dobro(n: int) -> int:, n: int diz que esperamos um inteiro na entrada; -> int diz que esperamos um inteiro no resultado. O último : ainda abre o corpo da função.',
    'A anotação não transforma nem confere o valor durante a execução. Se você precisa transformar um texto em número, ainda usa int ou float. Ferramentas como mypy e pyright podem procurar incompatibilidades, mas não são necessárias para o exercício desta aula.',
    'Comece anotando um tipo por valor. Em uma ampliação, list[str] descreve uma lista de textos e str | None descreve um texto ou a ausência de valor. O símbolo | separa as alternativas de tipo; não é uma conta nem um novo parágrafo.'
  ];
  all.modulos.theory.push('factorial(n), do módulo math, calcula o produto dos inteiros de 1 até n. Por exemplo factorial(4) devolve 24. É uma função pronta, não um operador novo.');
  all.git.example = 'comando = "git status"\nprint(comando)';
  all.git.challenge = 'Para revisar o comando antes de usá-lo no terminal: guarde o texto git diff em comando e mostre a variável. Este exercício de revisão não executa Git no navegador.';
  all.git.starter = '# Guarde o comando como texto e mostre.\n'; all.git.expected = 'git diff';
  all.logs.example = 'import logging\nlogging.basicConfig(level=logging.INFO, format="%(message)s", force=True)\nlogging.info("Processamento iniciado")';
  all.logs.challenge = 'Configure logging como no exemplo e registre Falha na conexão com logging.error. Use o formato %(message)s para a saída conter apenas a mensagem.';
  all.logs.starter = 'import logging\nlogging.basicConfig(level=logging.INFO, format="%(message)s", force=True)\n# Registre a mensagem no nível ERROR.\n';
  all.logs.theory.push('basicConfig configura o logger: level escolhe o mínimo exibido, format="%(message)s" mostra apenas a mensagem, e force=True refaz a configuração no laboratório. logging.error("texto") registra um evento de erro. Esses argumentos já estão fornecidos no desafio.');
  all.decoradores.theory.push('Dentro do wrapper, *args reúne argumentos posicionais e **kwargs reúne os nomeados. Ao chamar func(*args, **kwargs), você encaminha esses argumentos. A função interna consegue usar func, recebida pela função externa. @maiusculo sobre ola equivale a substituir ola por maiusculo(ola).');
  all.async.theory.push('asyncio.sleep(0.01) cria uma espera assíncrona curta; await aguarda seu término sem bloquear o loop. gather recebe as chamadas assíncronas e devolve resultados na ordem em que foram passadas, não na ordem em que terminaram.');
  all.analise.theory.push('mean(valores) calcula a média aritmética; median(valores) ordena os valores e encontra o central, ou a média dos dois centrais se a quantidade for par. Para [10, 20, 30], a mediana é 20.');
  all.deploy.theory.push('os.getenv("NOME", "padrão") lê uma variável de ambiente e usa o segundo argumento se ela não existir. Não é a mesma coisa que uma variável Python criada com =. No laboratório, teste com o nome do enunciado que não está configurado.');
  all.tcc.theory.push('requisitos.values() fornece os valores do dicionário. all(valores) devolve True quando todos são verdadeiros. Se qualquer requisito for False, o resultado será False. Aqui isso é uma checagem de lista de requisitos, não uma avaliação automática do sistema final.');

  return all;
}
