import { applyCurriculumReview } from './curriculum-review.js';
import { attachLessonGuides } from './lesson-guides.js';
import { attachLessonPuzzles } from './lesson-puzzles.js';
import { applyProjectReview } from './project-review.js';
// Each lesson contains authored theory, a runnable example, a separate challenge and a review question.
const lesson = (id, title, theory, example, challenge, starter, expected, question, options, answer = 0) => ({ id, title, theory: theory.split('|'), example, challenge, starter, expected, question, options, answer, minutes: 15, xp: 100 });
export const modules = [
  { id: 'fundamentos', number: '01', title: 'Primeiros passos com Python', category: 'Fundamentos', description: 'Comece do absoluto zero. Seu primeiro código é o primeiro passo de uma grande jornada.', color: 'purple', icon: 'Terminal', lessons: [
    lesson('ola', 'Olá, mundo!', 'Um programa é uma sequência de instruções. Python lê essas instruções de cima para baixo e executa o que você escreveu. Você não precisa instalar nada para começar aqui: nosso laboratório executa Python no navegador.|A função print() mostra uma informação na saída. Textos precisam estar entre aspas simples ou duplas. Os parênteses indicam os valores que você entrega à função. Maiúsculas e minúsculas fazem diferença: Print não é print.|Experimente mudar o texto e executar novamente. Se aparecer SyntaxError, confira aspas e parênteses: errar e ler a mensagem faz parte de programar.', 'print("Olá, mundo!")\nprint("Eu estou aprendendo Python.")', 'Mostre exatamente a frase: Meu primeiro programa em Python!', '# Escreva seu primeiro print abaixo\n', 'Meu primeiro programa em Python!', 'Qual instrução mostra uma mensagem na saída?', ['print("Olá!")', 'mostrar "Olá!"', 'Print = "Olá!"']),
    lesson('variaveis', 'Variáveis: dando nome às coisas', 'Uma variável associa um nome a um valor. Use = para atribuir: nome = "Ana". Depois, você pode usar o nome em outras instruções. O valor pode mudar ao longo do programa.|Prefira nomes que expliquem a intenção, como idade ou total_compra. Use letras, números e sublinhado, sem começar por número. O Python diferencia idade de Idade. O símbolo = atribui; ele não compara.', 'nome = "Ana"\nidade = 22\nprint(nome)\nprint(idade)', 'Crie a variável linguagem com o texto Python e mostre seu valor.', '# Crie a variável e use print\n', 'Python', 'O que faz idade = 20?', ['Associa o valor 20 ao nome idade', 'Compara idade com 20', 'Mostra 20 na tela']),
    lesson('tipos', 'Textos, números e booleanos', 'Python tem tipos para representar informações: str para texto, int para inteiros, float para números decimais e bool para True ou False. O tipo determina quais operações fazem sentido.|Use type(valor) para inspecionar o tipo. Conversões como int("12") e str(12) criam um valor de outro tipo. int("abc") gera ValueError porque o texto não representa um inteiro. Decimais usam ponto, não vírgula.', 'quantidade = int("3")\npreco = 12.5\nativo = True\nprint(quantidade * preco)', 'Converta o texto "21" em inteiro, multiplique por 2 e imprima o resultado.', 'texto = "21"\n# Converta e calcule\n', '42', 'Qual valor é do tipo bool?', ['True', '"True"', '1.5']),
    lesson('operadores', 'Contas e operadores', 'Use +, -, * e / para as quatro operações. A divisão / produz float. // calcula divisão inteira, % calcula o resto e ** calcula potência.|Parênteses mudam a ordem de avaliação. Multiplicação vem antes de adição. O resto é útil para descobrir se um número é par: numero % 2 == 0. Evite dividir por zero, pois isso gera ZeroDivisionError.', 'print(2 + 3 * 4)\nprint((2 + 3) * 4)\nprint(17 % 5)', 'Uma compra tem 3 produtos de R$ 20 e desconto de R$ 5. Calcule e mostre o total como inteiro.', 'quantidade = 3\npreco = 20\ndesconto = 5\n', '55', 'Qual operador calcula o resto da divisão?', ['%', '//', '**']),
    lesson('strings', 'Trabalhando com textos', 'Strings são sequências de caracteres. Você pode unir textos com + e interpolar valores com f-strings: f"Olá, {nome}". Métodos como strip(), lower() e upper() devolvem um novo texto.|Strings são imutáveis: os métodos não alteram o texto original. len(texto) conta caracteres. Um índice acessa uma posição, começando por zero: "Python"[0] é "P".', 'nome = "  ana  "\nprint(f"Olá, {nome.strip().title()}!")\nprint(len("Python"))', 'Remova os espaços nas extremidades e transforme o texto em maiúsculas.', 'texto = "  python  "\n', 'PYTHON', 'O que strip() remove por padrão?', ['Espaços e quebras nas extremidades', 'Todas as letras minúsculas', 'Todos os espaços do meio']),
    lesson('entrada', 'Entrada, saída e primeiros erros', 'input() lê uma linha e sempre retorna texto. Para calcular com uma entrada numérica, converta com int() ou float(). No laboratório, preencha o campo Entradas, uma resposta por linha, antes de executar.|Leia a última linha de um erro primeiro. NameError costuma indicar um nome inexistente; SyntaxError indica escrita inválida; TypeError pode indicar tipos incompatíveis. Use prints pequenos para verificar sua hipótese.', 'nome = "Estudante"\nprint(f"Boas-vindas, {nome}!")\n# Para testar entrada: nome = input("Seu nome: ")', 'Converta os dois textos em inteiros e imprima a soma.', 'a = "10"\nb = "25"\n', '35', 'Qual é o tipo do retorno de input()?', ['str', 'int', 'Depende do que foi digitado'])
  ]},
  { id: 'logica', number: '02', title: 'Lógica & resolução de problemas', category: 'Lógica', description: 'Ensine seus programas a decidir, repetir e resolver problemas.', color: 'blue', icon: 'Workflow', lessons: [
    lesson('condicoes', 'Decisões com if e else', 'if executa um bloco quando uma condição é verdadeira. else trata o caso contrário e elif testa outra condição. Use dois-pontos e quatro espaços para indentar cada bloco.|Comparações usam ==, !=, >, <, >= e <=. Uma condição como idade >= 18 produz um booleano. Pense também nos limites: se a regra é maior ou igual, o valor exatamente igual precisa funcionar.', 'idade = 20\nif idade >= 18:\n    print("Maior de idade")\nelse:\n    print("Menor de idade")', 'Mostre Aprovado se nota for pelo menos 7; caso contrário, mostre Revisar.', 'nota = 8\n', 'Aprovado', 'Qual símbolo compara igualdade?', ['==', '=', '=>']),
    lesson('booleanos', 'Combinando condições', 'and exige que as duas condições sejam verdadeiras. or exige pelo menos uma. not inverte o valor lógico. Use parênteses para deixar regras compostas claras.|Python faz avaliação de curto-circuito: em A and B, B só é avaliado quando A é verdadeiro. Isso permite verificar se um valor existe antes de acessar algo nele. Não confunda a palavra and com o operador de bits &.', 'idade = 19\ntem_ingresso = True\nprint(idade >= 18 and tem_ingresso)', 'Imprima True se a senha tiver pelo menos 8 caracteres e contiver um número 1.', 'senha = "python123"\n', 'True', 'Quando A and B é verdadeiro?', ['Quando ambos são verdadeiros', 'Quando qualquer um é verdadeiro', 'Quando ambos são falsos']),
    lesson('for', 'Repetições com for', 'for percorre os elementos de uma sequência. range(5) produz os inteiros de 0 a 4; o limite final não entra. range(1, 6) começa em 1 e termina em 5.|O corpo do laço precisa de indentação. Use uma variável acumuladora para combinar resultados. Antes de executar, simule as primeiras iterações no papel para entender como os valores mudam.', 'for numero in range(1, 4):\n    print(numero)', 'Some os números de 1 a 5 usando um laço e mostre apenas o total.', 'total = 0\n# Acumule os valores\n', '15', 'Quais números aparecem em range(3)?', ['0, 1 e 2', '1, 2 e 3', '0, 1, 2 e 3']),
    lesson('while', 'Repetições com while', 'while repete um bloco enquanto a condição for verdadeira. É útil quando você não conhece previamente a quantidade de repetições. Uma variável de controle deve caminhar para encerrar o laço.|Sem uma condição de saída, o programa pode repetir para sempre. No laboratório, o botão Interromper cancela a execução e um limite de tempo protege a interface. break encerra o laço e continue pula para a próxima iteração.', 'contador = 3\nwhile contador > 0:\n    print(contador)\n    contador -= 1', 'Use while para imprimir 1, 2 e 3, cada um em uma linha.', 'numero = 1\n', '1\n2\n3', 'Para que serve break?', ['Encerra o laço atual', 'Reinicia o programa', 'Pula somente o próximo print']),
    lesson('funcoes', 'Suas primeiras funções', 'Uma função reúne uma tarefa com nome. def define a função, parâmetros recebem dados e return devolve um resultado. Separar cálculo de apresentação permite testar e reutilizar a mesma lógica.|print mostra algo ao usuário; return entrega um valor para o código que chamou a função. Uma função sem return explícito retorna None. Evite depender de variáveis globais: prefira receber os dados necessários como argumentos.', 'def dobro(numero):\n    return numero * 2\n\nprint(dobro(6))', 'Crie a função quadrado(numero) e imprima quadrado(7).', 'def quadrado(numero):\n    # Substitua pass\n    pass\n\nprint(quadrado(7))', '49', 'Qual instrução devolve um valor da função?', ['return', 'print', 'input']),
    lesson('decomposicao', 'Decompondo um problema', 'Antes do código, descreva entradas, processamento e saída. Divida uma tarefa grande em funções pequenas. Para calcular uma média, por exemplo: receber notas, somar, dividir pela quantidade e classificar o resultado.|Teste um caso comum, um caso de limite e um caso inválido. A decomposição ajuda a localizar erros porque cada parte tem uma responsabilidade. Escreva nomes que descrevam o resultado e evite funções que fazem tudo.', 'def media(notas):\n    return sum(notas) / len(notas)\n\nprint(media([6, 8, 10]))', 'Implemente media e mostre a média das três notas fornecidas.', 'def media(notas):\n    pass\n\nprint(media([7, 8, 9]))', '8.0', 'Qual é uma boa primeira etapa para resolver um problema?', ['Definir entradas e saída esperada', 'Escrever o máximo de código', 'Ignorar os casos de limite'])
  ]},
  { id: 'estruturas', number: '03', title: 'Estruturas de dados', category: 'Intermediário', description: 'Organize informações e escolha a estrutura certa para cada problema.', color: 'orange', icon: 'Layers', lessons: [
    lesson('listas', 'Listas e índices', 'Listas guardam vários valores em ordem e podem ser alteradas. append adiciona um item, pop remove e devolve um item e len informa o tamanho. O primeiro índice é zero; -1 acessa o último elemento.|Cuidado ao copiar: b = a faz os dois nomes apontarem para a mesma lista. Para uma cópia superficial, use a.copy(). Acessar um índice inexistente gera IndexError. Verifique listas vazias antes de acessar posições.', 'tarefas = ["estudar", "praticar"]\ntarefas.append("revisar")\nprint(tarefas[-1])', 'Adicione o número 40 à lista e imprima a soma de todos os elementos.', 'numeros = [10, 20, 30]\n', '100', 'Qual índice acessa o primeiro elemento?', ['0', '1', '-1']),
    lesson('dicionarios', 'Dicionários: chave e valor', 'Dicionários associam chaves a valores. São úteis para representar uma pessoa, produto ou configuração. aluno["nome"] acessa uma chave; get permite um valor padrão se a chave não existir.|As chaves devem ser hashable, como strings, números ou tuplas de elementos hashable. Para percorrer pares, use items(). Não use acesso direto quando a ausência da chave for um caso esperado: isso gera KeyError.', 'aluno = {"nome": "Ana", "nivel": 1}\naluno["nivel"] += 1\nprint(aluno.get("nome"))', 'Aumente o estoque do produto em 5 e imprima o novo estoque.', 'produto = {"nome": "Livro", "estoque": 10}\n', '15', 'O que um dicionário associa?', ['Chaves a valores', 'Somente números a números', 'Somente índices a letras']),
    lesson('conjuntos', 'Tuplas e conjuntos', 'Tuplas são sequências imutáveis. Elas são úteis para agrupamentos fixos, como uma coordenada. Conjuntos (set) guardam valores únicos e permitem união, interseção e diferença.|A ordem de um conjunto não deve ser usada como regra do programa. Use sorted() para exibir em ordem previsível. Para criar um conjunto vazio use set(); {} cria um dicionário vazio.', 'a = {1, 2, 3}\nb = {3, 4}\nprint(sorted(a & b))', 'Remova as duplicatas usando set e imprima os valores ordenados.', 'numeros = [3, 1, 3, 2, 1]\n', '[1, 2, 3]', 'Qual estrutura elimina valores duplicados?', ['set', 'list', 'tuple']),
    lesson('comprehensions', 'Compreensões de listas', 'Uma list comprehension cria uma lista transformando e, opcionalmente, filtrando valores de uma sequência. A forma é [expressao for item in origem if condicao].|Prefira compreensões curtas. Se houver muitos níveis ou efeitos colaterais, um laço comum comunica melhor. Para grandes volumes, uma expressão geradora com parênteses pode evitar carregar tudo na memória.', 'dobros = [n * 2 for n in range(4)]\nprint(dobros)', 'Crie uma lista com os quadrados dos números de 1 a 4 e imprima.', '# Use uma compreensão\n', '[1, 4, 9, 16]', 'Para que serve o if em uma compreensão?', ['Filtrar os elementos', 'Ordenar automaticamente', 'Encerrar o programa']),
    lesson('ordenacao', 'Ordenando e filtrando', 'sorted() devolve uma nova lista ordenada. list.sort() altera a própria lista e retorna None. Use key para dizer qual critério será comparado, como o preço de um produto.|Uma função lambda é uma função pequena com uma expressão. reverse=True inverte a ordenação. Separe o filtro da ordenação quando isso deixar a intenção mais fácil de ler.', 'pessoas = [{"nome": "Bia", "idade": 25}, {"nome": "Ana", "idade": 20}]\nprint(sorted(pessoas, key=lambda p: p["idade"])[0]["nome"])', 'Ordene os preços do maior para o menor e imprima a lista.', 'precos = [15, 50, 10, 30]\n', '[50, 30, 15, 10]', 'O que sorted() retorna?', ['Uma nova lista ordenada', 'Sempre None', 'Uma string']),
    lesson('complexidade', 'Algoritmos e complexidade', 'Complexidade descreve como o trabalho cresce com a entrada. Percorrer n elementos é O(n). Dois laços completos aninhados podem ser O(n²). Uma busca binária em uma lista ordenada reduz a região de busca pela metade a cada passo: O(log n).|A consulta em um dicionário costuma ser O(1) em média, mas isso não significa tempo zero. Primeiro escreva uma solução correta, depois meça o gargalo. Considere também memória, legibilidade e tamanho real dos dados.', 'def contem(itens, alvo):\n    for item in itens:\n        if item == alvo:\n            return True\n    return False\n\nprint(contem([1, 4, 7], 4))', 'Use uma única passagem para contar quantas vezes 2 aparece e imprima a contagem.', 'numeros = [2, 1, 2, 3, 2, 4]\n', '3', 'Qual é o custo de percorrer uma lista inteira uma vez?', ['O(n)', 'O(1)', 'O(n²)'])
  ]},
  { id: 'objetos', number: '04', title: 'Orientação a objetos', category: 'Intermediário', description: 'Modele sistemas com classes, objetos e responsabilidades claras.', color: 'pink', icon: 'Boxes', lessons: [
    lesson('classes', 'Classes e objetos', 'Uma classe define dados e comportamentos de um conceito. Um objeto é uma instância dessa classe. Métodos são funções da classe e recebem a própria instância por meio do parâmetro self.|Use classes quando dados e regras precisam viver juntos. Uma função simples ainda é uma ótima escolha para transformações independentes. Não crie uma hierarquia de classes só para ter orientação a objetos.', 'class Saudacao:\n    def falar(self):\n        return "Olá!"\n\nprint(Saudacao().falar())', 'Crie a classe Aluno com um método estudar que retorna "Estudando Python". Instancie e imprima esse retorno.', 'class Aluno:\n    pass\n', 'Estudando Python', 'O que é uma instância?', ['Um objeto criado a partir de uma classe', 'Um arquivo de texto', 'Uma variável sempre global']),
    lesson('construtor', 'Construtores e atributos', '__init__ inicializa uma instância recém-criada. Atributos como self.nome guardam dados próprios de cada objeto. Argumentos do construtor permitem criar objetos com estados diferentes.|Atributos definidos na classe são compartilhados. Evite colocar listas mutáveis na classe quando cada objeto precisa de sua própria lista; inicialize-as no __init__. Valide o estado inicial para impedir objetos inválidos.', 'class Pessoa:\n    def __init__(self, nome):\n        self.nome = nome\n\nprint(Pessoa("Ana").nome)', 'Complete o construtor para guardar o nome e imprima o nome do produto.', 'class Produto:\n    def __init__(self, nome):\n        pass\n\nprint(Produto("Teclado").nome)', 'Teclado', 'Para que serve __init__?', ['Inicializar os atributos da instância', 'Apagar a classe', 'Importar bibliotecas']),
    lesson('encapsulamento', 'Encapsulamento e propriedades', 'Encapsular significa controlar como o estado muda. Um método depositar pode validar um valor antes de atualizar um saldo. Em Python, o prefixo _ sinaliza uso interno por convenção; ele não bloqueia acesso.|@property permite oferecer leitura com sintaxe de atributo e implementar validação em um setter. Exponha operações do domínio e mantenha suas regras em um único lugar, evitando alterações espalhadas pelo sistema.', 'class Conta:\n    def __init__(self):\n        self._saldo = 0\n    def depositar(self, valor):\n        if valor <= 0:\n            raise ValueError("Valor deve ser positivo")\n        self._saldo += valor\n    @property\n    def saldo(self):\n        return self._saldo\n\nc = Conta()\nc.depositar(20)\nprint(c.saldo)', 'Crie uma Conta, deposite 50 e depois 25 e imprima o saldo. Reutilize a classe do exemplo.', '# Cole a classe do exemplo e realize os depósitos\n', '75', 'O prefixo _ em um atributo indica o quê?', ['Uso interno por convenção', 'Criptografia automática', 'Acesso tecnicamente impossível']),
    lesson('heranca', 'Herança e polimorfismo', 'Herança permite especializar uma classe. Uma subclasse pode reutilizar e sobrescrever métodos. Polimorfismo permite usar objetos diferentes pela mesma interface, como chamar area() em várias formas.|Prefira herança para relações reais de especialização. Para montar comportamentos, composição costuma ser mais simples. Em Python, muitos contratos funcionam por comportamento: o objeto precisa oferecer o método esperado, sem necessariamente herdar de uma classe comum.', 'class Animal:\n    def som(self):\n        return "..."\n\nclass Gato(Animal):\n    def som(self):\n        return "Miau"\n\nprint(Gato().som())', 'Crie Cachorro herdando de Animal e sobrescreva som para retornar Au au. Imprima a chamada.', 'class Animal:\n    def som(self):\n        return "..."\n\n', 'Au au', 'O que é sobrescrever um método?', ['Definir uma versão do método na subclasse', 'Apagar todas as classes', 'Renomear um arquivo']),
    lesson('dataclasses', 'Dataclasses e composição', '@dataclass gera métodos úteis, como __init__ e __repr__, a partir dos atributos anotados. É uma boa ferramenta para representar dados com menos código repetitivo.|Composição cria um objeto que contém outros: um Pedido possui Itens. Para listas em dataclasses, use field(default_factory=list), evitando compartilhar uma lista entre instâncias. Anotações de tipo documentam a intenção, mas não validam valores automaticamente.', 'from dataclasses import dataclass\n\n@dataclass\nclass Item:\n    nome: str\n    preco: float\n\nprint(Item("Livro", 30).nome)', 'Crie uma dataclass Produto com nome e preco. Imprima o preco de Produto("Mouse", 80).', 'from dataclasses import dataclass\n\n', '80', 'As anotações de tipo validam valores automaticamente?', ['Não, precisam de validação ou ferramentas adicionais', 'Sim, sempre', 'Somente em dataclasses']),
    lesson('excecoes', 'Tratando exceções', 'try delimita um trecho que pode falhar. except trata uma classe de erro esperada. finally executa a limpeza mesmo quando há falha. Lance ValueError para informar que um argumento tem valor inválido.|Capture exceções específicas. Um except muito amplo pode esconder defeitos reais. Em vez de ignorar erros silenciosamente, preserve contexto e ofereça uma mensagem útil. Falhas são parte normal de entradas externas e operações de arquivo.', 'try:\n    numero = int("abc")\nexcept ValueError:\n    print("Digite um número inteiro")', 'Tente dividir 10 por 0 e capture ZeroDivisionError para imprimir Divisão inválida.', '# Use try e except\n', 'Divisão inválida', 'Por que capturar exceções específicas?', ['Para não esconder erros inesperados', 'Para deixar o programa mais lento', 'Porque except só aceita uma classe no Python'])
  ]},
  { id: 'dados', number: '05', title: 'Arquivos & banco de dados', category: 'Persistência', description: 'Salve dados, automatize tarefas e construa sistemas com SQLite.', color: 'teal', icon: 'Database', lessons: [
    lesson('arquivos', 'Lendo e escrevendo arquivos', 'open abre um arquivo. Use with para garantir o fechamento. Os modos r, w e a significam leitura, escrita com substituição e acréscimo. Informe encoding="utf-8" para trabalhar com acentos de forma previsível.|O modo w substitui o conteúdo existente. No laboratório, os arquivos vivem em um sistema virtual temporário; eles não são arquivos do seu computador. Para projetos locais, instale Python e use uma pasta dedicada.', 'with open("mensagem.txt", "w", encoding="utf-8") as arquivo:\n    arquivo.write("Olá, Python!")\nwith open("mensagem.txt", encoding="utf-8") as arquivo:\n    print(arquivo.read())', 'Escreva Aprender todos os dias em meta.txt, leia o arquivo e imprima seu conteúdo.', '# Use with open para escrever e ler\n', 'Aprender todos os dias', 'Qual modo substitui o conteúdo existente?', ['w', 'r', 'a']),
    lesson('json', 'JSON e troca de dados', 'JSON representa objetos, listas, textos, números, booleanos e null em um formato de texto. json.dumps transforma um objeto Python em string; json.loads faz o caminho inverso.|Nem todo objeto Python pode ser convertido diretamente: datas e classes precisam de uma representação. Nunca trate dados carregados como confiáveis sem validar sua estrutura. JSON é um formato de dados, não um banco de dados com transações.', 'import json\ndados = json.loads(\'{"nome": "Ana", "nivel": 2}\')\nprint(dados["nome"])', 'Leia o JSON e imprima a linguagem.', 'import json\ntexto = \'{"linguagem": "Python", "versao": 3}\'\n', 'Python', 'O que json.loads faz?', ['Converte texto JSON em objetos Python', 'Salva qualquer objeto no disco', 'Executa comandos Python']),
    lesson('csv', 'Planilhas e arquivos CSV', 'CSV organiza dados em linhas e colunas. O módulo csv trata delimitadores e aspas corretamente, evitando os problemas de separar texto manualmente por vírgula.|DictReader usa o cabeçalho como chaves. Valores lidos são texto e precisam de conversão quando representam números. Ao escrever arquivos reais, use newline="" e um encoding explícito. Valide colunas e células ausentes.', 'import csv\nimport io\narquivo = io.StringIO("nome,nota\\nAna,9\\nBia,8")\nfor linha in csv.DictReader(arquivo):\n    print(linha["nome"])', 'Leia o CSV e imprima a soma da coluna valor como inteiro.', 'import csv\nimport io\narquivo = io.StringIO("item,valor\\nLivro,30\\nCaneta,5")\n', '35', 'Como DictReader representa cada linha?', ['Como dicionário', 'Como número inteiro', 'Como classe SQL']),
    lesson('sql', 'Seu primeiro banco SQLite', 'Um banco relacional organiza dados em tabelas. SQL permite criar estruturas e inserir, consultar, atualizar e remover registros. SQLite funciona sem um servidor separado e está disponível no módulo sqlite3.|CREATE TABLE define colunas; INSERT inclui registros; SELECT consulta. Use chaves primárias para identificar registros. Na prática abaixo usamos :memory:, um banco temporário. Um caminho de arquivo permite persistência em um projeto local.', 'import sqlite3\ncon = sqlite3.connect(":memory:")\ncon.execute("CREATE TABLE alunos (nome TEXT)")\ncon.execute("INSERT INTO alunos VALUES (?)", ("Ana",))\nprint(con.execute("SELECT nome FROM alunos").fetchone()[0])\ncon.close()', 'Crie uma tabela produtos, insira Livro e consulte o nome, imprimindo Livro.', 'import sqlite3\ncon = sqlite3.connect(":memory:")\n', 'Livro', 'Qual comando consulta registros?', ['SELECT', 'INSERT', 'DELETE']),
    lesson('crud', 'CRUD e consultas seguras', 'CRUD significa criar, ler, atualizar e excluir. UPDATE altera registros e DELETE remove. A cláusula WHERE define quais registros são afetados; sem ela, a operação pode atingir toda a tabela.|Nunca monte SQL concatenando entrada do usuário. Passe parâmetros por placeholders, como WHERE id = ?. Isso separa código SQL dos dados. Nomes de tabela não podem ser parametrizados do mesmo modo: escolha-os de uma lista controlada.', 'import sqlite3\ncon = sqlite3.connect(":memory:")\ncon.execute("CREATE TABLE tarefas (id INTEGER PRIMARY KEY, titulo TEXT)")\ncon.execute("INSERT INTO tarefas VALUES (?, ?)", (1, "Estudar"))\ncon.execute("UPDATE tarefas SET titulo = ? WHERE id = ?", ("Praticar", 1))\nconsulta = con.execute("SELECT titulo FROM tarefas WHERE id = ?", (1,))\nprint(consulta.fetchone()[0])', 'Crie uma tabela com o estoque 10, atualize para 15 usando parâmetros e imprima o estoque consultado.', 'import sqlite3\ncon = sqlite3.connect(":memory:")\n', '15', 'Como enviar valores de usuário a uma consulta?', ['Com parâmetros e placeholders', 'Concatenando strings', 'Usando f-string no SQL']),
    lesson('transacoes', 'Relacionamentos e transações', 'Uma chave estrangeira relaciona um registro a outra tabela. JOIN combina dados relacionados. No SQLite, ative PRAGMA foreign_keys = ON em cada conexão para aplicar restrições de chaves estrangeiras.|Uma transação reúne mudanças que devem acontecer juntas. commit confirma e rollback desfaz mudanças pendentes. O contexto with con confirma em caso de sucesso e desfaz em caso de exceção, mas não fecha a conexão. Sempre feche quando terminar.', 'import sqlite3\ncon = sqlite3.connect(":memory:")\ncon.execute("CREATE TABLE vendas (valor INTEGER)")\nwith con:\n    con.executemany("INSERT INTO vendas VALUES (?)", [(10,), (20,)])\nprint(con.execute("SELECT SUM(valor) FROM vendas").fetchone()[0])\ncon.close()', 'Insira 25, 50 e 75 em uma tabela e consulte SUM(valor). Imprima o resultado.', 'import sqlite3\ncon = sqlite3.connect(":memory:")\n', '150', 'O que rollback faz?', ['Desfaz mudanças ainda não confirmadas', 'Apaga sempre o banco inteiro', 'Confirma uma transação'])
  ]},
  { id: 'web', number: '06', title: 'Desenvolvimento web & APIs', category: 'Avançado', description: 'Entenda HTTP e prepare serviços com validação e autenticação.', color: 'blue', icon: 'Globe', lessons: [
    lesson('http', 'Como a web funciona', 'Um cliente envia uma requisição HTTP e um servidor devolve uma resposta. A requisição tem método, endereço, cabeçalhos e, às vezes, corpo. GET busca recursos; POST costuma criar; PUT substitui e DELETE remove.|Status 2xx indica sucesso, 4xx indica problema na requisição e 5xx indica falha no servidor. Uma API precisa de contratos claros. O laboratório explora a lógica em Python; servidores HTTP persistentes devem rodar no seu ambiente local.', 'resposta = {"status": 200, "body": {"mensagem": "Olá, web!"}}\nprint(resposta["body"]["mensagem"])', 'Crie um dicionário de resposta com status 201 e imprima esse status.', '# Modele uma resposta de criação\n', '201', 'O que a família de status 4xx costuma indicar?', ['Um problema na requisição do cliente', 'Sucesso', 'Redirecionamento']),
    lesson('rest', 'Projetando uma API REST', 'Organize rotas em torno de recursos: /tarefas e /tarefas/{id}. Escolha métodos HTTP conforme a operação. Mantenha uma estrutura de erros consistente e documente filtros, paginação e respostas.|Idempotência significa que repetir a mesma operação tem o mesmo efeito pretendido. PUT e DELETE são definidos como idempotentes; POST não oferece essa garantia por padrão. A lógica de negócio deve poder ser testada sem depender do servidor.', 'tarefas = [{"id": 1, "titulo": "Estudar"}]\ndef buscar_tarefa(tarefa_id):\n    return next((t for t in tarefas if t["id"] == tarefa_id), None)\n\nprint(buscar_tarefa(1)["titulo"])', 'Implemente buscar_tarefa e imprima o título da tarefa de id 2.', 'tarefas = [{"id": 1, "titulo": "Ler"}, {"id": 2, "titulo": "Praticar"}]\n', 'Praticar', 'Qual rota representa melhor a coleção de tarefas?', ['/tarefas', '/fazerTudoAgora', '/arquivo.py']),
    lesson('validacao', 'Validando dados de entrada', 'Dados externos podem estar ausentes, malformados ou fora dos limites do domínio. Valide tipos, tamanhos e regras antes de persistir. Retorne mensagens que ajudem a corrigir o problema sem expor detalhes internos.|Frameworks como FastAPI podem usar modelos Pydantic para contratos de entrada. Mesmo com um framework, regras de negócio continuam necessárias: um número válido pode representar um preço negativo proibido pelo produto.', 'def validar_nome(nome):\n    if not isinstance(nome, str) or not nome.strip():\n        raise ValueError("Nome obrigatório")\n    return nome.strip()\n\nprint(validar_nome(" Ana "))', 'Escreva validar_preco que lança ValueError para preço negativo. Capture o erro de -5 e imprima Preço inválido.', '# Valide e trate a exceção\n', 'Preço inválido', 'Quando validar uma entrada externa?', ['Antes de usar ou persistir', 'Somente depois de salvar', 'Apenas se o usuário pedir']),
    lesson('autenticacao', 'Autenticação e autorização', 'Autenticação verifica quem é o usuário; autorização define o que ele pode fazer. Proteja cada recurso verificando o usuário e seu acesso. Estar autenticado não permite acessar dados de outras pessoas.|Senhas devem usar algoritmos próprios para senhas, como Argon2, por bibliotecas mantidas. Não armazene senhas em texto puro e não use SHA-256 simples como armazenamento de senha. Em produção, use HTTPS, sessões seguras e segredos fora do código.', 'def pode_editar(usuario_id, dono_id):\n    return usuario_id == dono_id\n\nprint(pode_editar(3, 3))', 'Implemente pode_editar: permita o dono ou um administrador. Imprima o resultado para usuário 2, dono 1, admin True.', 'def pode_editar(usuario_id, dono_id, admin=False):\n    pass\n\nprint(pode_editar(2, 1, True))', 'True', 'Qual pergunta a autorização responde?', ['O que este usuário pode fazer?', 'Qual é o nome do servidor?', 'Qual porta está aberta?']),
    lesson('paginacao', 'Paginação e filtros', 'Não devolva uma tabela inteira quando ela pode crescer. Paginação por página e tamanho é simples: o deslocamento é (pagina - 1) * tamanho. Use uma ordenação estável, preferencialmente com um desempate único.|Valide limites para evitar consultas caras. Paginação por cursor pode ser melhor para dados que mudam muito. Uma API deve documentar se a contagem total existe e como acessar a próxima página.', 'itens = list(range(1, 11))\npagina, tamanho = 2, 3\ninicio = (pagina - 1) * tamanho\nprint(itens[inicio:inicio + tamanho])', 'Obtenha a página 3 com tamanho 2 dos números de 1 a 10 e imprima a lista.', 'itens = list(range(1, 11))\npagina = 3\ntamanho = 2\n', '[5, 6]', 'Por que limitar o tamanho da página?', ['Para controlar uso de recursos e tempo de resposta', 'Para impedir qualquer busca', 'Para eliminar o banco de dados']),
    lesson('servicos', 'Da função ao servidor', 'Para executar uma API local, crie um ambiente virtual com python -m venv .venv, ative-o e instale fastapi e uvicorn. Um arquivo main.py pode declarar app = FastAPI() e usar @app.get("/saude") sobre uma função.|Execute python -m uvicorn main:app --reload durante o desenvolvimento. O servidor precisa rodar fora deste laboratório. Mantenha regras em serviços independentes e use a camada HTTP para traduzir entrada e saída. Consulte a documentação oficial antes de publicar.', 'def verificar_saude():\n    return {"status": "ok"}\n\nprint(verificar_saude()["status"])', 'Escreva um serviço criar_tarefa(titulo) que retorne um dicionário com titulo e concluida False. Imprima o valor concluida.', 'def criar_tarefa(titulo):\n    pass\n\nprint(criar_tarefa("Estudar")["concluida"])', 'False', 'Onde executar um servidor HTTP persistente desta formação?', ['No ambiente local ou em hospedagem apropriada', 'Dentro do print()', 'No arquivo JSON'])
  ]},
  { id: 'qualidade', number: '07', title: 'Engenharia de software', category: 'Avançado', description: 'Escreva código testável, mantenha versões e aprenda a entregar com confiança.', color: 'teal', icon: 'ShieldCheck', lessons: [
    lesson('testes', 'Testes automatizados', 'Um teste compara um comportamento observado com um resultado esperado. Organize-o em preparação, ação e verificação. Teste regras importantes, limites e falhas esperadas, evitando testes que só repetem a implementação.|assert é útil em exercícios e testes. Não o use para validar entradas de produção: ele pode ser desativado por otimizações. pytest facilita escrever testes como funções e unittest já acompanha o Python.', 'def somar(a, b):\n    return a + b\n\nassert somar(2, 3) == 5\nassert somar(-1, 1) == 0\nprint("Testes passaram")', 'Crie dobro, valide dobro(0) == 0 e dobro(4) == 8 com asserts. Imprima Testes passaram.', '# Função e dois casos de teste\n', 'Testes passaram', 'Qual caso vale a pena testar além do comum?', ['Limites e entradas inválidas', 'Somente o nome da função', 'A cor do editor']),
    lesson('tipagem', 'Tipagem e contratos', 'Type hints documentam os tipos esperados: def dobro(n: int) -> int. Ferramentas estáticas como mypy ou pyright podem encontrar incompatibilidades antes da execução.|A anotação não converte nem valida o valor em tempo de execução. Use tipos para esclarecer interfaces; use validação para entradas externas. Tipos como list[str] e str | None expressam coleções e valores opcionais em versões modernas do Python.', 'def saudacao(nome: str) -> str:\n    return f"Olá, {nome}"\n\nprint(saudacao("Ana"))', 'Crie somar(a: int, b: int) -> int e imprima somar(20, 22).', '# Use anotações de tipo\n', '42', 'O que um type hint faz sozinho?', ['Documenta a intenção do tipo', 'Converte qualquer entrada', 'Impede todo erro em execução']),
    lesson('modulos', 'Módulos e ambientes virtuais', 'Um arquivo .py é um módulo. import permite reutilizar seu conteúdo. Pacotes organizam módulos em diretórios. O bloco if __name__ == "__main__": diferencia execução direta de importação.|Use um ambiente virtual por projeto para isolar dependências. Registre versões em uma configuração de projeto e não versione .venv. Evite dar a seus arquivos nomes como json.py ou sqlite3.py, pois podem esconder módulos da biblioteca padrão.', 'from math import sqrt\nprint(sqrt(81))', 'Importe factorial de math e imprima o fatorial de 5.', '# Use a biblioteca padrão\n', '120', 'Para que serve um ambiente virtual?', ['Isolar dependências de um projeto', 'Hospedar um site automaticamente', 'Substituir o Git']),
    lesson('git', 'Git e histórico de mudanças', 'Git registra versões do projeto. git init inicia o repositório, git add prepara mudanças e git commit registra um conjunto com mensagem. git status mostra o estado atual e git diff mostra diferenças.|Use commits pequenos com intenção clara. .gitignore evita incluir arquivos locais, mas não remove segredos já versionados. Branches permitem trabalhar em mudanças isoladas; revise o diff antes de integrar. Os comandos Git devem ser executados no terminal local.', 'etapas = ["editar", "revisar", "adicionar", "commit"]\nprint(" → ".join(etapas))', 'Ordene a lista de versões usando a tupla como chave e imprima a última.', 'versoes = [(1, 2), (1, 10), (1, 3)]\n', '(1, 10)', 'Qual comando mostra alterações ainda não commitadas?', ['git diff', 'git init', 'git clone']),
    lesson('logs', 'Logs e diagnóstico', 'Logs registram acontecimentos úteis para investigar um sistema. Use níveis como DEBUG, INFO, WARNING e ERROR. Inclua contexto, por exemplo um identificador de requisição, sem registrar senhas ou tokens.|O módulo logging permite configurar formato e destino. Evite misturar mensagens operacionais com a saída normal da aplicação. Uma mensagem deve explicar o evento e seu contexto, sem revelar informações privadas desnecessárias.', 'import logging\nlogging.basicConfig(level=logging.INFO, force=True)\nlogging.info("Processamento iniciado")', 'Crie um dicionário de evento com nivel ERROR e mensagem Falha na conexão. Imprima apenas a mensagem.', '# Estruture o evento\n', 'Falha na conexão', 'Qual informação deve ficar fora dos logs?', ['Senhas e tokens', 'O nível da mensagem', 'O nome do evento']),
    lesson('arquitetura', 'Arquitetura e separação de responsabilidades', 'Separe apresentação, regras de negócio e persistência. Uma regra de desconto não precisa conhecer detalhes de HTTP ou SQL. Dependências recebidas como argumentos permitem substituir um banco por um objeto de teste.|Comece simples e extraia responsabilidades conforme o sistema cresce. Uma interface pequena e explícita costuma ajudar mais do que muitas camadas sem necessidade. Documente decisões e mantenha o fluxo dos dados fácil de seguir.', 'def total_com_desconto(subtotal, taxa):\n    return subtotal * (1 - taxa)\n\nprint(total_com_desconto(100, 0.1))', 'Crie total_com_desconto e imprima o resultado de subtotal 200 e taxa 0.25.', 'def total_com_desconto(subtotal, taxa):\n    pass\n\nprint(total_com_desconto(200, 0.25))', '150.0', 'Qual é uma vantagem de separar regras do banco?', ['Testar regras sem depender do banco real', 'Eliminar todas as funções', 'Dispensar validação'])
  ]},
  { id: 'avancado', number: '08', title: 'Python avançado & projeto final', category: 'Especialização', description: 'Explore concorrência, dados e entrega de um sistema de ponta a ponta.', color: 'purple', icon: 'Rocket', lessons: [
    lesson('geradores', 'Iteradores e geradores', 'Um gerador produz valores sob demanda com yield. Ao contrário de return, yield suspende a função preservando seu estado até a próxima iteração. Isso permite processar sequências sem construir uma lista completa.|Geradores se esgotam: uma segunda passagem no mesmo objeto pode não produzir nada. Eles são bons para pipelines e leitura progressiva de dados. Use list() só quando precisar materializar os valores na memória.', 'def contagem(limite):\n    for n in range(limite):\n        yield n\n\nprint(list(contagem(3)))', 'Crie um gerador pares que produza 0, 2 e 4. Imprima list(pares()).', 'def pares():\n    pass\n\nprint(list(pares()))', '[0, 2, 4]', 'O que yield permite?', ['Produzir valores preservando o estado da função', 'Encerrar sempre o programa', 'Executar SQL']),
    lesson('decoradores', 'Funções como objetos e decoradores', 'Funções podem ser passadas como argumentos e devolvidas por outras funções. Um decorador recebe uma função e devolve outra, adicionando comportamento como medição ou autorização.|Use functools.wraps para preservar metadados da função original. O wrapper geralmente recebe *args e **kwargs para encaminhar argumentos. Mantenha efeitos colaterais visíveis e evite esconder lógica de negócio importante em muitos decoradores.', 'from functools import wraps\ndef maiusculo(func):\n    @wraps(func)\n    def wrapper(*args, **kwargs):\n        return func(*args, **kwargs).upper()\n    return wrapper\n\n@maiusculo\ndef ola():\n    return "olá"\n\nprint(ola())', 'Crie um decorador que transforme o retorno em maiúsculas e aplique a uma função que retorna python. Imprima o retorno.', '# Use o padrão do exemplo\n', 'PYTHON', 'O que um decorador recebe normalmente?', ['Uma função', 'Somente uma string', 'Um arquivo SQL']),
    lesson('async', 'Concorrência com asyncio', 'async def define uma coroutine. await cede controle enquanto aguarda outra operação assíncrona. asyncio.gather coordena várias coroutines. Isso ajuda em trabalho com espera de rede, mas não acelera automaticamente cálculos intensivos de CPU.|Não use chamadas bloqueantes como time.sleep dentro de uma coroutine que deve manter o loop responsivo. No laboratório use await no nível superior; num script local, normalmente use asyncio.run(main()). Concorrência exige pensar em cancelamento, timeout e estado compartilhado.', 'import asyncio\nasync def dobro(n):\n    await asyncio.sleep(0.01)\n    return n * 2\n\nprint(await asyncio.gather(dobro(2), dobro(3)))', 'Crie uma coroutine quadrado e use gather para calcular 3² e 4². Imprima os resultados na lista.', 'import asyncio\n\n', '[9, 16]', 'Onde asyncio costuma ajudar?', ['Tarefas que aguardam operações de entrada e saída', 'Qualquer cálculo automaticamente', 'Somente leitura de variáveis']),
    lesson('analise', 'Análise de dados e estatística', 'Um fluxo de análise começa com uma pergunta, coleta dados, verifica qualidade, transforma e comunica resultados. A média pode ser distorcida por valores extremos; a mediana é o valor central da amostra ordenada.|O módulo statistics cobre operações básicas sem dependências. pandas é útil para tabelas maiores e transformações. Verifique valores ausentes, unidades e duplicatas. Uma correlação sozinha não estabelece causa e efeito.', 'from statistics import mean, median\nvalores = [10, 12, 13, 100]\nprint(mean(valores))\nprint(median(valores))', 'Use statistics.median para calcular a mediana da lista e imprima.', 'from statistics import median\nvalores = [10, 20, 30, 40, 500]\n', '30', 'Qual medida é menos sensível a valores extremos?', ['Mediana', 'Média aritmética', 'Soma']),
    lesson('deploy', 'Preparando a entrega', 'Entregar um sistema inclui configuração, dependências, migrações, logs e recuperação de falhas. Use variáveis de ambiente para configuração, mantenha segredos fora do repositório e forneça um .env.example sem valores reais.|Antes de publicar, rode testes, valide permissões, use HTTPS, configure backups e ensaie restauração. Uma integração contínua executa verificações a cada mudança. Documente como iniciar e como voltar a uma versão anterior; a entrega não termina quando o servidor sobe.', 'import os\nambiente = os.getenv("APP_ENV", "desenvolvimento")\nprint(ambiente)', 'Leia PYCAMPUS_MODO com valor padrão local e imprima. A variável não está definida neste laboratório.', 'import os\n', 'local', 'Onde devem ficar segredos de produção?', ['Em configuração segura fora do repositório', 'No README público', 'No código enviado ao navegador']),
    lesson('tcc', 'Projeto final: do requisito ao sistema', 'Seu projeto final reúne requisitos, modelagem, implementação, testes e entrega. Escolha um problema concreto e delimite a primeira versão. Escreva histórias de usuário e critérios observáveis de aceitação antes de desenvolver.|Construa um fluxo completo primeiro, como cadastrar um produto, salvar no banco e consultá-lo pela API. Depois acrescente autenticação, validação e testes. Entregue README, diagrama de dados, instruções de execução e uma demonstração. O projeto é uma autoavaliação de portfólio, não uma graduação reconhecida.', 'requisitos = {"cadastro": True, "testes": True, "documentacao": False}\nprint(all(requisitos.values()))', 'Calcule se todos os requisitos foram atendidos e imprima o resultado.', 'requisitos = {"cadastro": True, "testes": True, "documentacao": True}\n', 'True', 'O que torna um critério de aceitação útil?', ['Ser observável e verificável', 'Ser o mais vago possível', 'Não ter relação com o usuário'])
  ]}
];
const conditions = modules[1].lessons[0];
conditions.title = 'Decisões com if, elif e else';
conditions.theory.push('Conexão com sua faculdade: na Unidade 1, aula 1 (páginas 11–12), o exemplo calcula a média de quatro notas e aprova com média >= 6. A aula 2 aprofunda operadores relacionais, condições e o caso de um cinema. A palavra elif significa "senão, se": ela só é testada quando as condições anteriores falham. else não recebe uma condição.');
conditions.theory.push('Para notas decimais, use float(input()), como 7.5. Calcule media = (nota_1 + nota_2 + nota_3 + nota_4) / 4 antes do if. Os dois-pontos abrem o bloco e quatro espaços indicam o que pertence a ele. Compare 5.9, 6.0 e 6.1 para verificar o limite.');
conditions.example = 'nota_1 = 7.5\nnota_2 = 6.0\nnota_3 = 8.0\nnota_4 = 6.5\nmedia = (nota_1 + nota_2 + nota_3 + nota_4) / 4\n\nif media >= 6:\n    print("Aprovado")\nelse:\n    print("Reprovado")';
conditions.challenge = 'Regra fictícia para praticar elif: nota >= 7 mostra Aprovado; senão, nota >= 5 mostra Recuperação; senão, mostra Reprovado. Escreva os três caminhos. Para nota = 6, a saída deve ser Recuperação. Teste também 4 e 8 antes de voltar para 6.';
conditions.starter = 'nota = 6\n# Escreva if, elif e else abaixo\n';
conditions.expected = 'Recuperação';
conditions.question = 'Com nota 8, em uma cadeia if nota >= 7 / elif nota >= 5 / else, quais blocos executam?';
conditions.options = ['Somente o bloco do if', 'O if e o elif, porque 8 também é maior que 5', 'Todos os três blocos'];
const reviewedLessons = applyCurriculumReview(modules);
attachLessonGuides(reviewedLessons);
attachLessonPuzzles(reviewedLessons);
export const lessons = modules.flatMap(m => m.lessons.map(l => ({ ...l, moduleId: m.id, moduleTitle: m.title, moduleNumber: m.number }))).map((l, index) => {
  const offset = index % l.options.length;
  return { ...l, options: [...l.options.slice(offset), ...l.options.slice(0, offset)], answer: (l.answer - offset + l.options.length) % l.options.length };
});
export const projects = [
  { id: 'calculadora', module: 0, title: 'Calculadora de orçamento', subtitle: 'Transforme seus primeiros comandos em uma ferramenta útil.', icon: 'Calculator', color: 'purple', level: 'Iniciante', hours: '2–4 h', brief: 'Construa um programa de terminal que recebe a renda mensal e as despesas, calcula o saldo e informa se o orçamento está positivo. Comece com valores fixos; depois acrescente input e conversões.', requirements: ['Receber renda e pelo menos três despesas', 'Calcular despesas totais e saldo disponível', 'Mostrar valores com duas casas decimais', 'Tratar entradas que não são números', 'Documentar como executar e demonstrar três cenários'] },
  { id: 'quiz', module: 1, title: 'Quiz interativo de Python', subtitle: 'Um jogo de perguntas com pontuação e feedback.', icon: 'Brain', color: 'blue', level: 'Iniciante', hours: '3–5 h', brief: 'Crie um quiz de terminal com cinco perguntas de Python. Separe a exibição, validação de resposta e cálculo de pontuação em funções. Permita jogar novamente sem reiniciar o programa.', requirements: ['Criar cinco perguntas com alternativas', 'Validar respostas fora das alternativas', 'Calcular acertos e mostrar feedback por questão', 'Usar funções e permitir nova partida', 'Testar zero acertos, todos os acertos e entrada inválida'] },
  { id: 'tarefas', module: 2, title: 'Gerenciador de tarefas', subtitle: 'Seu primeiro CRUD, construído por você.', icon: 'ListTodo', color: 'orange', level: 'Intermediário', hours: '4–6 h', brief: 'Crie um gerenciador de tarefas no terminal. Cada tarefa tem id, título, prioridade e status. Use uma lista de dicionários e um menu para cadastrar, listar, concluir e excluir tarefas.', requirements: ['Cadastrar tarefas com identificadores únicos', 'Listar e filtrar por status ou prioridade', 'Concluir e excluir por identificador', 'Tratar tarefa inexistente e título vazio', 'Separar funções e documentar exemplos de uso'] },
  { id: 'banco', module: 3, title: 'Simulador de conta digital', subtitle: 'Classes e regras de negócio trabalhando juntas.', icon: 'Wallet', color: 'pink', level: 'Intermediário', hours: '5–8 h', brief: 'Modele clientes e contas. Implemente depósito, saque, transferência e extrato. É um simulador educacional sem conexão com dinheiro real. Use Decimal para representar valores monetários.', requirements: ['Modelar Cliente e Conta com responsabilidades claras', 'Impedir saque maior que o saldo e valores negativos', 'Transferir sem deixar estado parcial em uma falha', 'Manter histórico com data, tipo e valor', 'Testar saldo insuficiente, transferência e arredondamento'] },
  { id: 'estoque', module: 4, title: 'Sistema de estoque', subtitle: 'Produtos, movimentações e persistência de verdade.', icon: 'Package', color: 'teal', level: 'Intermediário', hours: '8–12 h', brief: 'Construa um sistema local com SQLite para produtos e movimentações. Cada movimentação precisa registrar entrada ou saída, quantidade e data. Crie um relatório e exporte para CSV.', requirements: ['Criar tabelas relacionadas com chaves e restrições', 'Cadastrar, consultar e atualizar produtos', 'Registrar movimentos em transações e impedir estoque negativo', 'Usar consultas parametrizadas e exportar relatório CSV', 'Documentar backup e demonstrar restauração do banco'] },
  { id: 'api', module: 5, title: 'API de hábitos', subtitle: 'Um serviço web para acompanhar pequenas conquistas.', icon: 'Globe', color: 'blue', level: 'Avançado', hours: '10–16 h', brief: 'Em ambiente local, use FastAPI, Pydantic e SQLite para oferecer uma API de hábitos com usuários e registros diários. Consulte fastapi.tiangolo.com para instalação e exemplos. Separe rotas, serviços e persistência.', requirements: ['Criar endpoints de cadastro, listagem, edição e remoção', 'Validar contratos e oferecer paginação e erros consistentes', 'Autenticar e impedir acesso a hábitos de outros usuários', 'Persistir registros e evitar duplicata do mesmo dia', 'Documentar instalação, variáveis e exemplos de requisição'] },
  { id: 'qualidade-projeto', module: 6, title: 'Uma aplicação pronta para evoluir', subtitle: 'Refatore, teste e automatize a validação da sua API.', icon: 'ShieldCheck', color: 'teal', level: 'Avançado', hours: '8–12 h', brief: 'Pegue a API da etapa anterior e torne sua manutenção previsível. Acrescente testes com pytest, verificação de tipos, logs e integração contínua. Foque regras importantes e acesso indevido, não apenas cobertura numérica.', requirements: ['Separar regras de negócio das rotas e do banco', 'Cobrir sucesso, limites e autorização com testes', 'Configurar checagem de tipos e formatação', 'Criar pipeline de CI e registrar logs sem dados secretos', 'Documentar arquitetura e uma decisão técnica com tradeoffs'] },
  { id: 'final', module: 7, title: 'Projeto final: seu sistema completo', subtitle: 'Do problema real ao seu projeto de portfólio.', icon: 'Rocket', color: 'purple', level: 'Projeto final', hours: '20–40 h', brief: 'Construa um sistema de gestão para uma biblioteca, pequeno comércio ou estudo pessoal. Inclua interface web, API Python, banco relacional, usuários e permissões. Defina escopo, construa um fluxo completo e entregue uma demonstração.', requirements: ['Definir problema, usuários e cinco critérios de aceitação', 'Entregar interface, API e banco com migrações', 'Implementar autenticação, autorização e validação de entrada', 'Testar fluxos centrais, documentar deploy e restauração de backup', 'Entregar repositório, README, diagrama de dados e demonstração'] }
];
applyProjectReview(projects);
export const resources = [
  { title: 'Tutorial oficial de Python', description: 'A referência para acompanhar sua formação.', url: 'https://docs.python.org/pt-br/3/tutorial/' },
  { title: 'Documentação do FastAPI', description: 'Próximo passo para os projetos de APIs.', url: 'https://fastapi.tiangolo.com/' },
  { title: 'Guia do pytest', description: 'Testes para seus projetos locais.', url: 'https://docs.pytest.org/en/stable/getting-started.html' },
  { title: 'Pro Git em português', description: 'Controle de versão, branches e colaboração.', url: 'https://git-scm.com/book/pt-br/v2' }
];
