// A disciplina Linguagem de Programação (Anhanguera), na ordem da ementa.
//
// Por que esta trilha existe separada das 8 etapas: as etapas são sequenciais — moduleIsOpen
// exige toda etapa anterior completa — e o estudante está na etapa 02. Pôr a Unidade 2 e a
// Unidade 3 da faculdade como etapa 09 as deixaria travadas atrás de 48 aulas e 8 projetos,
// que é exatamente o contrário do que serve para quem tem prova chegando. Aqui não há trava:
// a faculdade cobra este conteúdo agora.
//
// Todo exemplo é o código do professor, corrigido só onde ele não roda (o PDF tem erros de
// digitação: `texto` virando `texto2`, f-string sem aspas, `anos` usado antes de existir).
// Nenhuma saída esperada foi escrita de cabeça: scripts/check-faculdade.mjs executa os 24
// programas no Pyodide real e falha se algum divergir.

const aula = (id, titulo, unidade, teoria, exemplo, desafio, starter, esperado, pergunta, opcoes, resposta = 0, extras = {}) =>
  ({ id, titulo, unidade, teoria: teoria.split('|'), exemplo, desafio, starter, esperado, pergunta, opcoes, resposta, minutos: 20, ...extras });

export const unidades = [
  {
    id: 'u2', numero: '2', titulo: 'Explorando Recursos do Python', cor: 'purple', icone: 'Boxes',
    resumo: 'Sequências, listas, tuplas, conjuntos, dicionários, NumPy, classes, herança, módulos e Matplotlib.',
    competencia: 'Identificar os pilares da orientação a objetos e sua utilização na linguagem de programação com Python.'
  },
  {
    id: 'u3', numero: '3', titulo: 'Introdução à Análise de Dados com Python', cor: 'blue', icone: 'ChartNoAxesColumn',
    resumo: 'SQL e SQLite, CRUD, pandas, manipulação de dados e visualização com Matplotlib e Seaborn.',
    competencia: 'Compreender os principais recursos de banco de dados e bibliotecas na linguagem Python.'
  }
];

export const aulasDaFaculdade = [
  // ————————————————————————————— Unidade 2 —————————————————————————————
  aula('u2a1', 'Estruturas de dados I: sequências, listas e tuplas', 'u2',
    'Em Python tudo gira em torno de objetos. Sequências são estruturas que guardam coleções ordenadas, indexadas por inteiros não negativos: o primeiro elemento está no índice 0 e o último na posição n - 1, onde n é o tamanho.|As operações comuns a toda sequência, do Quadro 1 da apostila: x in s testa se um item existe; s + t concatena; n * s repete; s[i] acessa uma posição; s[i:j] fatia da posição i até antes de j; s[i:j:k] fatia com passo k; len(s) dá o tamanho; min(s) e max(s) dão o menor e o maior; s.count(x) conta ocorrências.|Texto (str) também é sequência, e é imutável: não dá para trocar uma letra por atribuição. Listas são sequências mutáveis — dá para adicionar, remover e alterar. O método index devolve a posição de um valor na lista.|Tuplas são sequências imutáveis. Crie com parênteses: vazia com (), com valores com ("a", "b", "c"), ou com o construtor tuple(). Uma vez criada, não muda. enumerate() devolve a posição e o valor a cada volta, o que evita controlar um contador à mão.',
    ['texto = "Explorando a diversidade de linguagens de programacao com Python."',
      'print(f"Tamanho do texto = {len(texto)}")',
      'print(f"Python in texto = {\'Python\' in texto}")',
      'print(f"Quantidade de e no texto = {texto.count(\'e\')}")',
      'print(f"As 5 primeiras letras sao: {texto[:5]}")',
      '',
      'cores = ["vermelho", "azul", "verde"]',
      'for cor in cores:',
      '    print(f"Posicao = {cores.index(cor)}, cor = {cor}")',
      '',
      'vogais = ("a", "e", "i", "o", "u")',
      'print(f"Tipo do objeto vogais = {type(vogais)}")',
      'for p, x in enumerate(vogais):',
      '    print(f"Posicao = {p}, valor = {x}")'].join('\n'),
    'Crie a tupla dias com "seg", "ter" e "qua". Mostre o tamanho dela, depois percorra com enumerate mostrando "0 seg", "1 ter" e "2 qua", um por linha.',
    'dias = ("seg", "ter", "qua")\n# Mostre o tamanho e depois percorra com enumerate\n',
    '3\n0 seg\n1 ter\n2 qua',
    'Qual é a diferença essencial entre lista e tupla?',
    ['A lista é mutável e a tupla não pode ser alterada depois de criada', 'A tupla só aceita texto e a lista só aceita números', 'A tupla é mais rápida porque não usa índices'],
    0),

  aula('u2a2', 'Estruturas de dados II: conjuntos, dicionários e NumPy', 'u2',
    'Um conjunto (set) guarda elementos únicos, sem repetição, como um conjunto da matemática. Ele habilita união, interseção e diferença, e serve para eliminar duplicados. Crie com chaves — {"a", "b"} — ou com set(iteravel). add(valor) acrescenta e remove(valor) retira.|Dicionários (dict) associam chaves a valores e são mutáveis. Quatro formas de criar, todas equivalentes: começar vazio com {} e atribuir por chave; escrever os pares direto — {"nome": "Maria", "idade": 25}; usar dict([("nome", "Maria")]); ou combinar duas listas com dict(zip(chaves, valores)).|Acesse um valor com dicionario[chave] e atribua com dicionario[chave] = novo_valor.|NumPy é a biblioteca para computação científica: arrays multidimensionais e operações em massa. Importe com import numpy as np. Um array opera elemento a elemento: my_array ** 2 eleva todos ao quadrado de uma vez, sem laço. np.sum soma tudo. Aqui no PyCampus o NumPy é baixado sozinho quando você escreve o import.',
    ['meu_conjunto = set()',
      'meu_conjunto.add(10)',
      'meu_conjunto.add(20)',
      'meu_conjunto.add(20)',
      'print("Conjunto:", sorted(meu_conjunto))',
      'meu_conjunto.remove(20)',
      'print("Depois de remover 20:", sorted(meu_conjunto))',
      '',
      'dici_1 = {}',
      'dici_1["nome"] = "Maria"',
      'dici_1["idade"] = 25',
      'dici_2 = {"nome": "Maria", "idade": 25}',
      'dici_3 = dict([("nome", "Maria"), ("idade", 25)])',
      'dici_4 = dict(zip(["nome", "idade"], ["Maria", 25]))',
      'print(dici_1 == dici_2 == dici_3 == dici_4)',
      '',
      'import numpy as np',
      'my_array = np.array([1, 2, 3, 4, 5])',
      'print("Ao quadrado:", my_array ** 2)',
      'print("Soma:", np.sum(my_array))',
      'print("Indice 2:", my_array[2])'].join('\n'),
    'A lista notas tem valores repetidos. Use um conjunto para descobrir quantos valores DIFERENTES existem e mostre só esse número.',
    'notas = [7, 8, 7, 9, 8, 10]\n# Use set() e len() em uma linha\n',
    '4',
    'Para que serve um conjunto (set)?',
    ['Guardar valores únicos, sem repetição', 'Guardar pares de chave e valor', 'Guardar valores em ordem fixa que não muda'],
    0),

  aula('u2a3', 'Classes, métodos e herança', 'u2',
    'A orientação a objetos organiza o código em torno de objetos, cada um representando algo do mundo real. A classe é o molde; o objeto é o que nasce dele. Uma classe reúne atributos (os dados, o estado) e métodos (os comportamentos).|Os cinco componentes que a apostila cobra: atributos, métodos, encapsulamento (juntar dados e comportamento numa entidade e controlar o acesso), herança (uma classe herdar de outra) e polimorfismo (classes diferentes respondendo de formas diferentes à mesma mensagem).|Em Python, class abre a classe. O método __init__ é o construtor: roda quando o objeto é criado e inicializa os atributos. self é a convenção que se refere à própria instância — self.nome = nome guarda o valor naquele objeto.|A classe-filha é declarada com o nome da classe-pai entre parênteses: class Carro(Veiculo). Ela herda atributos e métodos e pode reescrevê-los. super().__init__(...) chama o construtor da classe-pai em vez de repetir o código dele. Python aceita herança múltipla: class Filha(Pai1, Pai2).',
    ['class Veiculo:',
      '    def __init__(self, marca, modelo, ano):',
      '        self.marca = marca',
      '        self.modelo = modelo',
      '        self.ano = ano',
      '        self.velocidade = 0',
      '',
      '    def acelerar(self, incremento):',
      '        self.velocidade += incremento',
      '',
      '    def status(self):',
      '        return f"Marca: {self.marca}, Modelo: {self.modelo}, Ano: {self.ano}, Velocidade: {self.velocidade} km/h"',
      '',
      'class Carro(Veiculo):',
      '    def __init__(self, marca, modelo, ano, potencia):',
      '        super().__init__(marca, modelo, ano)',
      '        self.potencia = potencia',
      '',
      '    def acelerar(self, incremento):',
      '        self.velocidade += incremento + self.potencia',
      '',
      'carro1 = Carro("Toyota", "Corolla", 2022, 150)',
      'carro1.acelerar(50)',
      'print(carro1.status())'].join('\n'),
    'A classe Pessoa já está pronta. Crie a pessoa1 com nome Joao e idade 30, mostre o cumprimento e depois a idade depois de um aniversário.',
    ['class Pessoa:',
      '    def __init__(self, nome, idade):',
      '        self.nome = nome',
      '        self.idade = idade',
      '',
      '    def cumprimentar(self):',
      '        return f"Ola, meu nome e {self.nome}."',
      '',
      '    def aniversario(self):',
      '        self.idade += 1',
      '',
      '# Crie pessoa1, mostre o cumprimento, faca aniversario e mostre a nova idade',
      ''].join('\n'),
    'Ola, meu nome e Joao.\n31',
    'Para que serve super().__init__(...) na classe-filha?',
    ['Chamar o construtor da classe-pai em vez de repetir o código dele', 'Criar um objeto novo da classe-pai', 'Impedir que a classe-filha altere os atributos'],
    0),

  aula('u2a4', 'Módulos, bibliotecas e Matplotlib', 'u2',
    'Módulos são componentes de código que reúnem funções, e servem para reaproveitar código entre programas. Na prática um módulo é uma biblioteca de funções: math traz funções matemáticas, os traz funções do sistema operacional.|Três formas de usar um módulo. A primeira carrega tudo e você chama pelo nome do módulo: import math, depois math.sqrt(25). A segunda dá um apelido: import math as m, depois m.sqrt(25). A terceira carrega só o que você vai usar: from math import sqrt, e então sqrt(25) direto.|Os módulos se classificam em três tipos. Built-in vêm no interpretador e não precisam de instalação: math, os, sys, random, datetime, re, collections. De terceiros são criados fora e distribuídos pelo PyPI, instalados com pip install nome — é o caso de NumPy, pandas e Matplotlib. Próprios são os que você mesmo escreve.|Matplotlib é a biblioteca de gráficos mais usada em Python. O módulo pyplot dá a interface de alto nível: import matplotlib.pyplot as plt. plt.plot faz um gráfico de linha, plt.bar um de barras, plt.xlabel e plt.ylabel rotulam os eixos, plt.title dá o título e plt.show exibe. Aqui no navegador o gráfico não abre em janela; use plt.gcf() para conferir que a figura foi montada.',
    ['import math',
      'print("sqrt(25) =", math.sqrt(25))',
      '',
      'import math as m',
      'print("log2(1024) =", m.log2(1024))',
      '',
      'from math import factorial',
      'print("factorial(5) =", factorial(5))',
      '',
      'import matplotlib',
      'matplotlib.use("Agg")',
      'import matplotlib.pyplot as plt',
      '',
      'meses = ["Janeiro", "Fevereiro", "Marco", "Abril", "Maio"]',
      'vendas = [120, 90, 150, 80, 200]',
      'plt.bar(meses, vendas, color="royalblue")',
      'plt.xlabel("Mes")',
      'plt.ylabel("Vendas (em unidades)")',
      'plt.title("Vendas Mensais")',
      'print("Barras no grafico:", len(plt.gca().patches))',
      'print("Titulo:", plt.gca().get_title())'].join('\n'),
    'Importe o módulo math com o apelido m e mostre a raiz quadrada de 144 como número inteiro.',
    '# Importe com apelido e mostre a raiz de 144\n',
    '12',
    'O que import math as m muda em relação a import math?',
    ['Passa a chamar as funções por m.sqrt em vez de math.sqrt', 'Carrega só a função sqrt na memória', 'Instala o módulo math antes de usar'],
    0),

  // ————————————————————————————— Unidade 3 —————————————————————————————
  aula('u3a1', 'Banco de dados: SQL, SQLite e CRUD', 'u3',
    'SQL é a linguagem para falar com bancos relacionais, padronizada pelo ANSI em 1986. Suas instruções se agrupam em três categorias, e a prova cobra os nomes: DDL (Data Definition Language) define a estrutura — CREATE, ALTER, DROP; DML (Data Manipulation Language) mexe nos dados — SELECT, INSERT, UPDATE, DELETE; DCL (Data Control Language) controla o acesso — GRANT e REVOKE.|SQLite é um banco completo escrito em C que não precisa de servidor separado: ele lê e escreve direto num arquivo. Um banco inteiro, com tabelas, índices e visões, cabe num único arquivo. Python traz o módulo sqlite3 embutido.|CRUD é Create, Read, Update e Delete. Os passos são sempre os mesmos: abrir a conexão, criar um cursor e executar o comando, gravar com commit e fechar. Sem o commit, o SQLite desfaz o que foi feito.|Nunca monte a consulta concatenando valores dentro do texto. Use ? como marcador e passe os valores separados: cursor.execute("INSERT INTO Contatos (nome) VALUES (?)", (nome,)). Isso é o que impede injeção de SQL. fetchone devolve um registro; fetchall devolve todos.',
    ['import sqlite3',
      '',
      'conn = sqlite3.connect(":memory:")',
      'cursor = conn.cursor()',
      'cursor.execute("""',
      '    CREATE TABLE IF NOT EXISTS Produtos (',
      '        id INTEGER PRIMARY KEY,',
      '        nome TEXT NOT NULL,',
      '        preco REAL NOT NULL,',
      '        estoque INTEGER',
      '    )',
      '""")',
      '',
      'cursor.execute("INSERT INTO Produtos (nome, preco, estoque) VALUES (?, ?, ?)", ("Camiseta", 19.99, 50))',
      'conn.commit()',
      '',
      'cursor.execute("SELECT * FROM Produtos")',
      'print("Depois do INSERT:", cursor.fetchall())',
      '',
      'cursor.execute("UPDATE Produtos SET preco = ? WHERE id = ?", (24.99, 1))',
      'conn.commit()',
      'cursor.execute("SELECT nome, preco FROM Produtos")',
      'print("Depois do UPDATE:", cursor.fetchone())',
      '',
      'cursor.execute("DELETE FROM Produtos WHERE id = ?", (1,))',
      'conn.commit()',
      'cursor.execute("SELECT * FROM Produtos")',
      'print("Depois do DELETE:", cursor.fetchall())',
      'conn.close()'].join('\n'),
    'A tabela Contatos já está criada e aberta. Insira o contato Maria com o e-mail maria@email.com usando parâmetros com ?, confirme com commit e mostre o resultado de SELECT * FROM Contatos.',
    ['import sqlite3',
      'conn = sqlite3.connect(":memory:")',
      'cursor = conn.cursor()',
      'cursor.execute("CREATE TABLE Contatos (id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT, email TEXT)")',
      '# Insira Maria com parametros, confirme e mostre a tabela',
      ''].join('\n'),
    "[(1, 'Maria', 'maria@email.com')]",
    'CREATE TABLE pertence a qual categoria do SQL?',
    ['DDL, porque define a estrutura do banco', 'DML, porque manipula os dados', 'DCL, porque controla o acesso'],
    0),

  aula('u3a2', 'pandas: Series e DataFrame', 'u3',
    'pandas é a biblioteca de código aberto para manipular e analisar dados em tabelas e séries temporais. Ela é construída sobre o NumPy. Importe com import pandas as pd.|Duas estruturas sustentam tudo. A Series é unidimensional, como uma lista com rótulos. O DataFrame é bidimensional, como uma tabela com linhas e colunas.|Crie uma Series a partir de uma lista — pd.Series([10, 20, 30]) — e os índices viram 0, 1, 2. A partir de um dicionário, as chaves viram os índices e os valores viram os dados. O parâmetro index define rótulos próprios.|Sobre a Series você aplica cálculos direto: mean() dá a média, sum() a soma, max() e min() os extremos. Um DataFrame nasce de um dicionário de listas, em que cada chave é uma coluna.|pandas lê dados estruturados de muitas origens, sempre com o prefixo read_: read_csv, read_json, read_html, read_excel, read_sql. Para escrever, os métodos to_: to_csv, to_json, to_excel, to_sql. read_html procura as tabelas <table> de uma página e devolve uma lista de DataFrames.',
    ['import pandas as pd',
      '',
      'series1 = pd.Series([10, 20, 30, 40, 50])',
      'print(series1.sum(), series1.mean())',
      '',
      'data = {"A": 100, "B": 200, "C": 300}',
      'series2 = pd.Series(data)',
      'print("Indices:", list(series2.index))',
      '',
      'dados = {"Nome": ["Alice", "Bob", "Carol", "David", "Eve"], "Idade": [25, 30, 22, 35, 28]}',
      'serie_idades = pd.Series(dados["Idade"], index=dados["Nome"])',
      'print(serie_idades)',
      'print("Media de Idades:", serie_idades.mean())',
      '',
      'df = pd.DataFrame(dados)',
      'print("Formato do DataFrame:", df.shape)',
      'print("Colunas:", list(df.columns))'].join('\n'),
    'Monte uma Series com as idades 20, 30 e 40 e mostre só a média, sem texto em volta.',
    'import pandas as pd\n# Crie a Series e mostre a media\n',
    '30.0',
    'Qual é a diferença entre Series e DataFrame?',
    ['A Series é unidimensional e o DataFrame é bidimensional, como uma tabela', 'A Series só guarda números e o DataFrame só guarda texto', 'A Series é imutável e o DataFrame é mutável'],
    0),

  aula('u3a3', 'pandas: capturar, transformar e extrair informação', 'u3',
    'Dados brutos quase nunca chegam prontos. A etapa de captura e transformação é o que os torna utilizáveis, e é onde mora a maior parte do trabalho real.|Linhas duplicadas distorcem qualquer conta. drop_duplicates() remove as repetidas; keep="last" mantém a última ocorrência e inplace=True salva a mudança no próprio DataFrame, em vez de devolver uma cópia.|Criar uma coluna nova é uma atribuição: df["nova_coluna"] = valor. Se o valor for único, o pandas o repete em todas as linhas. Se for um cálculo entre colunas, ele é feito linha a linha — df["preco"] = df["receita"] / df["quantidade"].|Para extrair informação existem dois caminhos principais. loc seleciona por rótulo: df.loc[0] traz a linha 0, df.loc[[0, 2]] traz duas linhas. O teste booleano compara uma coluna inteira e devolve True ou False para cada linha; usado dentro de df[...] ele filtra — df[df["preco"] > 50] traz só as linhas em que o preço passa de 50.',
    ['import pandas as pd',
      '',
      'data = {',
      '    "nome": ["Produto A", "Produto B", "Produto C", "Produto A", "Produto E"],',
      '    "quantidade": [3, 1, 4, 3, 2],',
      '    "tipo": ["Eletronico", "Vestuario", "Alimento", "Eletronico", "Alimento"],',
      '    "receita": [120, 80, 60, 120, 90]',
      '}',
      'df = pd.DataFrame(data)',
      'print("Antes:", df.shape)',
      '',
      'df.drop_duplicates(keep="last", inplace=True)',
      'print("Depois de tirar duplicadas:", df.shape)',
      '',
      'df["preco do item"] = df["receita"] / df["quantidade"]',
      'print(df.loc[1])',
      '',
      'itens_acima_de_50 = df[df["preco do item"] > 50]',
      'print("Itens acima de 50 reais:", list(itens_acima_de_50["nome"]))'].join('\n'),
    'O DataFrame vendas já existe. Mostre só os nomes dos produtos cuja receita passa de 100, como uma lista.',
    ['import pandas as pd',
      'vendas = pd.DataFrame({"nome": ["A", "B", "C"], "receita": [120, 80, 150]})',
      '# Filtre com teste booleano e mostre a lista de nomes',
      ''].join('\n'),
    "['A', 'C']",
    'O que faz df[df["preco"] > 50]?',
    ['Devolve só as linhas em que a coluna preco passa de 50', 'Troca por 50 todos os preços menores', 'Ordena o DataFrame pela coluna preco'],
    0),

  aula('u3a4', 'Visualização de dados: Matplotlib, pandas e Seaborn', 'u3',
    'Gráficos contam a história dos dados. Três caminhos, do mais manual ao mais especializado.|Matplotlib é a base. O pyplot cria e gerencia a figura e o eixo sozinho, e você chama plt.plot, plt.bar, plt.xlabel, plt.title. O outro estilo, orientado a objetos, cria figura e eixos explicitamente com plt.subplots e chama métodos sobre eles.|pandas tem plot() embutido, construído sobre o Matplotlib: df.plot(x="Produto", y="qtde_vendida", kind="bar") — e kind aceita bar, pie, line e outros.|Seaborn é construído sobre o Matplotlib e traz conjuntos de dados prontos, como tips. O que o diferencia é o parâmetro estimator do barplot: por padrão ele calcula a MÉDIA, mas aceita sum para somar e len para contar. Essa escolha muda a conclusão.|A apostila insiste num ponto que costuma cair em prova: o mesmo dado, com estimadores diferentes, conta histórias diferentes. Na soma os homens parecem gastar muito mais; com len você descobre que eles são muitos mais na base. Interpretar gráfico exige olhar o contexto, não só a barra mais alta.',
    ['import matplotlib',
      'matplotlib.use("Agg")',
      'import matplotlib.pyplot as plt',
      'import pandas as pd',
      '',
      'x = [1, 2, 3, 4, 5]',
      'y = [2, 4, 1, 3, 5]',
      'plt.plot(x, y)',
      'plt.xlabel("Eixo X")',
      'plt.ylabel("Eixo Y")',
      'plt.title("Exemplo de Grafico de Linha")',
      'print("Linhas no grafico:", len(plt.gca().lines))',
      'plt.close()',
      '',
      'dados = {"Produto": ["A", "B", "C"], "qtde_vendida": [33, 50, 45]}',
      'df = pd.DataFrame(dados)',
      'eixo = df.plot(x="Produto", y="qtde_vendida", kind="bar")',
      'print("Barras pelo pandas:", len(eixo.patches))',
      'plt.close()',
      '',
      'contas = pd.DataFrame({"time": ["Lunch", "Lunch", "Dinner", "Dinner", "Dinner"],',
      '                       "total_bill": [10.0, 20.0, 30.0, 40.0, 50.0]})',
      'print("Media por periodo:")',
      'print(contas.groupby("time")["total_bill"].mean())',
      'print("Soma por periodo:")',
      'print(contas.groupby("time")["total_bill"].sum())',
      'print("Contagem por periodo:")',
      'print(contas.groupby("time")["total_bill"].count())'].join('\n'),
    'Monte um gráfico de barras com os meses Jan e Fev e as vendas 120 e 90, ponha o título Vendas e mostre quantas barras a figura tem, no formato: Barras: 2',
    ['import matplotlib',
      'matplotlib.use("Agg")',
      'import matplotlib.pyplot as plt',
      '# Monte as barras, ponha o titulo e mostre a contagem',
      ''].join('\n'),
    'Barras: 2',
    'No barplot do Seaborn, o que o parâmetro estimator faz?',
    ['Escolhe a conta da barra: média por padrão, ou sum, ou len', 'Escolhe a cor das barras', 'Escolhe quantas barras cabem no gráfico'],
    0)
];

// As oito tarefas "Aplicando a aula!" e "É Hora de Praticar!" dos slides e das apostilas. São o
// que o professor propõe como aplicação, então são o que mais se parece com a avaliação.
export const tarefasDaFaculdade = [
  { id: 't-condicionais', unidade: 'u2', titulo: 'Três filmes por faixa etária', origem: 'Slides · Estruturas condicionais',
    enunciado: 'Há 3 filmes por semana. O primeiro é para menores de 12 anos; o segundo para maiores ou iguais a 12 e menores de 18; o terceiro para maiores ou iguais a 18. Considere também a disponibilidade de ingressos.',
    pratica: ['if', 'elif', 'else', 'operadores relacionais', 'and'] },
  { id: 't-repeticao', unidade: 'u2', titulo: 'Notas de cinco filmes', origem: 'Slides · Estruturas de repetição',
    enunciado: 'Percorra os cinco filmes (Filme 1 a Filme 5) e receba para cada um uma nota de 1 a 5. Deixe sempre uma forma da pessoa encerrar o programa antes do fim.',
    pratica: ['for', 'while', 'range', 'break', 'continue'] },
  { id: 't-funcoes', unidade: 'u2', titulo: 'Média de notas automatizada', origem: 'Slides · Funções em Python',
    enunciado: 'Automatize a média de notas dos alunos. Parta do código da aula anterior e melhore usando funções definidas por você, com parâmetro e retorno.',
    pratica: ['def', 'parâmetro', 'return', 'lambda'] },
  { id: 't-convidados', unidade: 'u2', titulo: 'Convidados que não confirmaram', origem: 'Unidade 2 · Aula 1',
    enunciado: 'Você gerencia a lista de convidados de uma festa e a lista de quem confirmou presença. Identifique quem ainda não confirmou, para convidar de novo.',
    pratica: ['tupla', 'lista', 'list comprehension', 'not in'] },
  { id: 't-evento', unidade: 'u2', titulo: 'Evento científico: regiões, afiliações e interesses', origem: 'Unidade 2 · Aula 2',
    enunciado: 'Participantes de várias regiões se inscreveram num evento científico, cada um com localização, afiliação e áreas de interesse. Use conjuntos para as regiões distintas, um dicionário para agrupar as afiliações e NumPy para achar a área de interesse mais popular.',
    pratica: ['set', 'dict', 'numpy', 'np.unique', 'np.argmax'] },
  { id: 't-biblioteca', unidade: 'u2', titulo: 'Catálogo de livros com gráfico', origem: 'Unidade 2 · Aula 5',
    enunciado: 'Gerencie informações de livros de uma biblioteca e faça a contagem de livros por ano de publicação. Use uma classe Livro, uma lista como acervo e um gráfico da distribuição por ano.',
    pratica: ['class', '__init__', '__str__', 'lista', 'matplotlib'] },
  { id: 't-contatos', unidade: 'u3', titulo: 'Tabela de contatos com CRUD', origem: 'Unidade 3 · Aula 1',
    enunciado: 'Crie a tabela Contatos para a comunicação da empresa, guardando nome, e-mail e telefone. Pratique as quatro operações: inserir os contatos, ler e exibir, atualizar um telefone e excluir um contato.',
    pratica: ['sqlite3', 'CREATE TABLE', 'executemany', 'SELECT', 'UPDATE', 'DELETE'] },
  { id: 't-funcionarios', unidade: 'u3', titulo: 'Funcionários no SQLite', origem: 'Unidade 3 · Aula 5',
    enunciado: 'Desenvolva um programa de gerenciamento de funcionários numa tabela SQLite, com id, nome, cargo e salário. Percorra o ciclo completo: criar, inserir, consultar, atualizar e deletar.',
    pratica: ['sqlite3', 'cursor', 'commit', 'CRUD'] }
];

export const aulasDaUnidade = id => aulasDaFaculdade.filter(a => a.unidade === id);
export const tarefasDaUnidade = id => tarefasDaFaculdade.filter(t => t.unidade === id);
export const aulaDaFaculdade = id => aulasDaFaculdade.find(a => a.id === id) || null;
