import { useState } from 'react';
import { Icon } from './ui.jsx';
import { historyStatuses, historyReport, reviewQuestions, reviewSummary, HISTORY_LIMIT } from './history.js';
import { normalizeLumiNotes, LUMI_NOTES_LIMIT } from './lumi-notes.js';
import './lesson.css';
export default function HistoryView({ state, update, download }) {
  const [filter, setFilter] = useState('all');
  const items = state.history || [];
  const lumiNotes = normalizeLumiNotes(state.lumiNotes);
  const hasEntries = Boolean(items.length || lumiNotes.length);
  const revisoes = reviewSummary(state);
  const shown = [...items].reverse().filter(item => filter === 'all' || (filter === 'error' ? item.status !== 'success' : item.source === 'lesson'));
  return <>
    <div className="page-heading"><div><div className="eyebrow">APRENDER É TENTAR, ENTENDER E REVISAR</div><h1>Diário de aprendizagem</h1><p>Suas tentativas, descobertas e orientações, para acompanhar sua evolução com calma.</p></div><button className="button primary" disabled={!hasEntries} aria-describedby={!hasEntries ? 'history-share-help' : undefined} onClick={() => download(historyReport(state), `pycampus-aprendizado-${new Date().toISOString().slice(0, 10)}.md`, 'text/markdown;charset=utf-8')}>Compartilhar com Astra ↓</button></div>
    <section className="card history-intro"><div className="step-head"><span className="icon-tile blue"><Icon name="BookOpenCheck" size={21} /></span><div><div className="eyebrow">O QUE VOCÊ JÁ PRATICOU</div><h2>Uma conversa baseada no que você praticou</h2></div></div><p>Ao executar código em uma aula ou no laboratório, guardamos uma cópia do código, entradas, saída e erros. As orientações do Lumi também ficam resumidas aqui para você retomar o raciocínio depois.</p><p id="history-share-help"><strong>Compartilhar com Astra</strong> baixa um relatório. {!hasEntries && 'O botão libera depois da primeira execução ou orientação registrada. '}Anexe esse arquivo à nossa conversa e peça uma revisão. Não há envio automático nem acompanhamento em segundo plano.</p><p className="small muted">O histórico mantém até {HISTORY_LIMIT} tentativas recentes e {LUMI_NOTES_LIMIT} orientações resumidas, com limite de espaço. Registros muito grandes são abreviados. Exporte regularmente para guardar tentativas antigas. O backup das configurações também inclui o diário.</p></section>
    <div className="project-summary"><span>{items.length} tentativas registradas</span><span>{items.filter(i => i.status === 'success').length} executaram sem erro</span><span>{items.filter(i => i.status === 'error').length} erros de código</span><span>{lumiNotes.length} orientações do Lumi</span></div>
    {revisoes.length > 0 && <section className="card review-queue" aria-labelledby="titulo-revisao-diario"><div className="step-head"><span className="icon-tile orange"><Icon name="Target" size={21} /></span><div><div className="eyebrow">PRÓXIMOS PONTOS DE ATENÇÃO</div><h2 id="titulo-revisao-diario">Seu diário indica o que revisar</h2></div></div><p className="small muted">Não é uma nota: são os assuntos onde uma nova tentativa pode consolidar seu raciocínio.</p><div className="review-queue-list">{revisoes.map(item => <div className="review-queue-item" key={item.titulo}><div><strong>{item.titulo}</strong><small>{item.tentativas} {item.tentativas === 1 ? 'tentativa para revisar' : 'tentativas para revisar'}</small></div><p>{item.pergunta}</p></div>)}</div></section>}
    <div className="tab-row">{[['all', 'Todas as tentativas'], ['error', 'Erros e interrupções'], ['lesson', 'Exercícios das aulas']].map(([value, label]) => <button key={value} className={filter === value ? 'active' : ''} onClick={() => setFilter(value)}>{label}</button>)}</div>
    {!shown.length && <section className="card empty history-empty"><span className="history-empty-icon"><Icon name="Sprout" size={28} /></span><div><div className="eyebrow">{items.length ? 'ESTE FILTRO ESTÁ LIVRE' : 'SEU DIÁRIO COMEÇA NO PRIMEIRO TESTE'}</div><h3>{items.length ? 'Nenhuma tentativa neste filtro' : 'Seu próximo teste já pode entrar no diário'}</h3><p>Execute um programa no laboratório ou em uma aula. O código, a saída e os erros ficam organizados aqui para você revisar depois.</p></div><div className="history-empty-steps"><span><strong>1</strong> Escreva</span><span><strong>2</strong> Execute</span><span><strong>3</strong> Revise</span></div></section>}
    <div className="history-list">{shown.map(item => <details key={item.id} className="card history-entry"><summary><div><strong>{item.title || 'Laboratório livre'}</strong><small>{new Date(item.startedAt).toLocaleString('pt-BR')} · {item.source === 'lesson' ? 'Exercício de aula' : 'Prática livre'}</small></div><span className={`pill ${item.status === 'success' ? 'teal' : 'orange'}`}>{historyStatuses[item.status]}</span></summary><div className="history-detail">
      {item.matched !== null && <p className={item.matched ? 'success-text' : 'muted'}>{item.matched ? 'A saída correspondeu ao desafio.' : 'Executou, mas a saída não correspondeu ao desafio.'} Isso não avalia sozinho sua compreensão.</p>}
      {item.truncated && <p className="hint">Registro abreviado por limite de tamanho.</p>}
      <h3>Código executado</h3><pre className="example-code">{item.code}</pre>
      {item.stdin && <><h3>Entradas usadas</h3><pre className="example-code">{item.stdin}</pre></>}
      <h3>Saída ou mensagem de erro</h3><pre className="example-code">{item.output || '(Sem saída)'}</pre>
      <section className="history-questions"><h3>Perguntas para revisar</h3><p className="small muted">Sugestões automáticas com base no código, para orientar a conversa. Não são uma avaliação de domínio.</p><ul>{reviewQuestions(item).map(question => <li key={question}>{question}</li>)}</ul></section>
      <label className="form-label">Minha reflexão — o que entendi? Usei alguma dica?<textarea aria-label={`Reflexão sobre ${item.id}`} maxLength={1500} placeholder="Ex.: O primeiro if verdadeiro encerra a escolha. Testei 11, 12 e 18. Ainda quero praticar sem olhar o exemplo." value={item.reflection || ''} onChange={event => { const reflection = event.target.value; update(s => ({ ...s, history: (s.history || []).map(entry => entry.id === item.id ? { ...entry, reflection } : entry) })); }} /></label><span className="small muted">A reflexão é salva junto ao seu progresso.</span>
    </div></details>)}</div>
    {lumiNotes.length > 0 && <section className="card history-intro"><div className="step-head"><span className="icon-tile purple"><Icon name="Sparkles" size={21} /></span><div><div className="eyebrow">ORIENTAÇÕES QUE VOCÊ PEDIU</div><h2>Conversas com o Lumi</h2></div></div><p className="small muted">Uma orientação ajuda a seguir, mas só a sua próxima tentativa mostra se a ideia ficou clara.</p><div className="history-list">{[...lumiNotes].reverse().map(note => <details key={note.id} className="card history-entry"><summary><div><strong>{note.title}</strong><small>{new Date(note.at).toLocaleString('pt-BR')} · {note.activityId}</small></div><span className={`pill ${note.fonte === 'escrita' ? 'blue' : 'purple'}`}>{note.fonte === 'escrita' ? 'Dica escrita' : 'Lumi'} {note.level}/4</span></summary><div className="history-detail"><h3>Sua pergunta</h3><p>{note.question}</p><h3>{note.fonte === 'escrita' ? 'A dica escrita que apareceu' : 'O que o Lumi explicou'}</h3><p>{note.tip}</p><p className="small muted">Aula de referência: {note.lessonId}</p></div></details>)}</div></section>}
  </>;
}
