import { useState } from 'react';
import { fileNameFor, parseRepo } from './project-steps.js';

import { readmeFields, buildReadme } from './project-documentation.js';
import ProjectGrade from './ProjectGrade.jsx';

export default function ProjectDelivery({ project, state, update, download, code }) {
  const [part, setPart] = useState('readme'), [index, setIndex] = useState(0), [message, setMessage] = useState('');
  const doc = state.projectReadmes?.[project.id] || {};
  const [key, label, hint] = readmeFields[index];
  const file = fileNameFor(project.id);
  const save = value => update(s => ({ ...s, projectReadmes: { ...s.projectReadmes, [project.id]: { ...s.projectReadmes?.[project.id], [key]: value } } }));
  return <section className="card studio-publish"><h2>Da construção à entrega</h2><p>Escreva sobre o que você fez. Depois baixe seu código e o README para compartilhar.</p><div className="tab-row"><button aria-pressed={part === 'readme'} onClick={() => setPart('readme')}>1 · Escrever README</button><button aria-pressed={part === 'files'} onClick={() => setPart('files')}>2 · Baixar e testar</button><button aria-pressed={part === 'github'} onClick={() => setPart('github')}>3 · Publicar no GitHub</button></div>
    {part === 'readme' && <><p>README.md é o arquivo que apresenta seu projeto. O símbolo # cria um título. Você escreve o conteúdo; a plataforma organiza as seções.</p><label className="practice-field">{label}<textarea aria-label="Texto do README" maxLength={3000} value={doc[key] || ''} onChange={e => save(e.target.value)} placeholder={hint} /></label><p>{hint}</p><div className="button-row"><button className="button outline" disabled={index === 0} onClick={() => setIndex(index - 1)}>← Pergunta anterior</button>{index < readmeFields.length - 1 ? <button className="button primary" onClick={() => setIndex(index + 1)}>Próxima pergunta →</button> : <button className="button primary" onClick={() => setPart('files')}>Ir para os arquivos →</button>}</div><details className="guided-example"><summary>Ver como está ficando meu README</summary><pre className="example-code">{buildReadme(project, doc)}</pre></details><a href="https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes" target="_blank" rel="noreferrer">O que colocar em um README · guia oficial</a></>}
    {part === 'files' && <><h3>Confira fora da plataforma</h3><ol className="guided-actions"><li>Baixe os dois arquivos pelos botões abaixo. Se alguma seção do README estiver vazia, volte e escreva sua explicação.</li><li>Crie uma pasta para este projeto e coloque os dois arquivos nela. No Windows, use o botão direito → Novo → Pasta.</li><li>Instale Python pelo <a href="https://www.python.org/downloads/" target="_blank" rel="noreferrer">site oficial</a> se ainda não tiver. Reabra o terminal depois da instalação.</li><li>Abra a pasta no Explorador de Arquivos. Clique com o botão direito no espaço vazio → Abrir no Terminal. Digite <code>python {file}</code>. Se o Windows não reconhecer python, tente <code>py {file}</code>.</li><li>Responda às perguntas do programa ou siga o menu. Compare com o caso que você registrou no README. Se houver erro, volte ao passo correspondente no estúdio.</li><li>Se o programa grava um banco ou arquivo, encerre e execute de novo para testar a persistência. Os dados do ambiente Python do navegador são temporários.</li></ol><div className="button-row"><button className="button primary" onClick={() => download(code, file, 'text/x-python')}>Baixar {file}</button><button className="button outline" onClick={() => download(buildReadme(project, doc), 'README.md', 'text/markdown')}>Baixar README.md</button><button className="text-button" onClick={() => setPart('github')}>Arquivos conferidos: ver publicação →</button></div></>}
    {part === 'github' && <><h3>Publicar no GitHub, pelo navegador</h3><p>Publicar o código compartilha os arquivos; isso não hospeda um programa Python funcionando como site. Você pode manter o repositório privado.</p><ol className="guided-actions"><li>Entre em <a href="https://github.com" target="_blank" rel="noreferrer">github.com</a>. Use Sign up para criar conta ou Sign in para entrar.</li><li>Abra <a href="https://github.com/new" target="_blank" rel="noreferrer">New repository</a>. Dê um nome curto ao projeto, por exemplo meu-primeiro-python. Escolha Public ou Private.</li><li>Marque Add a README file para criar uma página inicial. Clique em Create repository.</li><li>Na página criada, abra Add file → Upload files. Escolha seu arquivo {file} e o README.md baixado. O README enviado substitui o inicial.</li><li>Escreva uma mensagem como “Adiciona primeira versão do projeto”. Um commit é o registro dessa alteração.</li><li>Se aparecer a opção de gravar na branch atual, confirme para seu repositório de estudo. Se escolher uma nova branch, use Propose changes, depois Create pull request e, após revisar, Merge pull request para juntar à principal.</li><li>Volte à página principal do repositório. Abra {file} e confira o conteúdo. Seu README deve aparecer abaixo da lista de arquivos.</li><li>Copie o endereço da página principal para o campo abaixo. Em uma próxima melhoria, envie o arquivo alterado novamente e use uma mensagem que explique a mudança.</li></ol><a href="https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository" target="_blank" rel="noreferrer">Guia oficial: enviar arquivos</a><form onSubmit={e => { e.preventDefault(); const link = new FormData(e.currentTarget).get('repo').trim(); if (link && !parseRepo(link)) { setMessage('Use o endereço principal: https://github.com/usuario/repositorio'); return; } update(s => ({ ...s, projectLinks: { ...s.projectLinks, [project.id]: link } })); setMessage('Link salvo. Agora peça a avaliação do Lumi logo abaixo.'); }}><label className="form-label">Link do meu projeto<input key={project.id} name="repo" type="url" defaultValue={state.projectLinks?.[project.id] || ''} placeholder="https://github.com/usuario/repositorio" /></label><button className="button primary" type="submit">Salvar link</button><p role="status">{message}</p></form>
      <ProjectGrade project={project} state={state} update={update} /></>}
  </section>;
}
